### ISSUE TITLE
List of action names?

### ISSUE THREAD

**Issue by StefanKarpinski** [marta-file-manager/marta-issues#1014]
I haven't been able to find a list of action names anywhere. I'm trying to bind a key to the "Move To Inactive" action but haven't been able to guess the action name for it.

**Comment by mhtawfiq** [comment]
Bring up the Actions prompt Shift+Command+P by default, start typing until the action you want is listed in the results then press and hold Option.

You will see the action name displayed. (core.move.inactive) in this case.

**Comment by StefanKarpinski** [comment]
I see "Move To Inactive" displayed, I do not see "core.move.inactive" anywhere.

**Comment by mhtawfiq** [comment]
It will be displayed next to "Move to Inactive Pane" when you press and hold Option.

I attached a screenshot.

![Untitled](https://github.com/marta-file-manager/marta-issues/assets/18537015/e4ae8b0d-abc9-40aa-a2dd-8e8ddc3ea4d0)

**Comment by StefanKarpinski** [comment]
Ah, I had missed the "press and hold Option" part. Thanks. Might be worth adding to the docs somewhere.
