### ISSUE TITLE
[Feature request] Move the config file and custom themes to `~/.config/marta`

### ISSUE THREAD

**Issue by aravezskinteeth** [marta-file-manager/marta-issues#1028]
I know that the config file and custom themes are inside `~/Application Support/org.yanex.marta`, however in my opinion, this is not intuitive. It's easier to symlink configuration files and custom themes from a dotfiles repository to `~/.config/marta`.

**Comment by yanex** [comment]
Unlike Linux, "Application Support" is a standard place for macOS applications to store their configuration. On my machine, only Copilot stores its settings in `.config`.
