### ISSUE TITLE
Remember terminal height

### ISSUE THREAD

**Issue by vedmant** [marta-file-manager/marta-issues#1031]
Probably related to https://github.com/marta-file-manager/marta-issues/issues/1017

When I open terminal it always takes most of the window height and doesn't remember when I adjust the height.

https://github.com/marta-file-manager/marta-issues/assets/5052406/95350ff9-360a-46cf-b0e5-b15383fe4044

Sonoma 14.2.1 (23C71)
Marta 0.8.1

**Comment by yanex** [comment]
Seems like duplicate of #1017.
