### ISSUE TITLE
Display mode: Expanding Table view

### ISSUE THREAD

**Issue by vedmant** [marta-file-manager/marta-issues#1034]
Would be really nice to be able to expand folders in place like the List view in Finder or PathFinder, it's still possible to keep all the columns of Table view.

![Monosnap Macintosh HD 2024-02-20 13-20-10](https://github.com/marta-file-manager/marta-issues/assets/5052406/81c5e4e5-fe41-44cf-9073-084261adc891)

**Comment by yanex** [comment]
Duplicate of #577.
