### ISSUE TITLE
Marta.sh is down / domain expired 

### ISSUE THREAD

**Issue by smuemd** [marta-file-manager/marta-issues#1037]
Visiting https://marta.sh/ leads me to a placeholder site with the message: "The domain has expired. Is this your domain? [Renew now](https://www.namecheap.com/domains/registration/results/?domain=marta.sh)"

**Comment by tbsvttr** [comment]
Yeah, same problem here.

**Comment by yanex** [comment]
Thank you for reporting this! I renewed the domain, it should work again soon.
