### ISSUE TITLE
Terminal theme - colors not applied

### ISSUE THREAD

**Issue by AdrianSimionov** [marta-file-manager/marta-issues#1040]
With the exception of background and foreground colors, I am not able to change any other color for terminal. Changing the terminal theme seems to apply a new color to background and foreground only. Cursor and selection always remain the same default color.

Tests done by modifying any default terminal themes.

**Comment by yanex** [comment]
It turned out that the built-in `ettyTheme` files had incorrect option names (`cursor` and `cursorText`). The correct names are `caret` and `caretText`. In the next version, I will update the themes.
