### ISSUE TITLE
Right click triggers pop up menu when `rightClickSelect true` is on

### ISSUE THREAD

**Issue by seekiu** [marta-file-manager/marta-issues#1065]
Just upgraded 0.8.2 (thanks for the great work btw) and found this issue. 

Basically I'm used to setting `rightClickSelect true` so that a single right click on an item would select it, and press and hold right button would show the pop up menu. This has been working fine with 0.8.1, but with 0.8.2 a single right click would trigger both selection and pop up menu, the latter having about 1 second lag.

I did a quick search in preference and didn't find any new setting related to this. So I suppose this is a bug?

**Comment by yanex** [comment]
Thanks for the report! As it's a degradation, I will probably publish a hotfix release.

**Comment by Rhywun** [comment]
Hi, is there any update on this issue/hotfix?

It is marked `completed` but I don't see a version 0.8.3.

Liking the app so far, esp. the configurability and possibilities for scripting!
