### ISSUE TITLE
Modifying Keybinding wont apply

### ISSUE THREAD

**Issue by vitusli** [marta-file-manager/marta-issues#1068]
Hi there! I love Marta. It is beautiful, fast and full with amazing features. 

One thing I need help with after really trying everything is: my keybindings won't change whatever I try. I added my config as well as a screenshot. Does anyone know, why this does not work? All my other settings I set up just work. 

Any help is appreciated!

![image](https://github.com/user-attachments/assets/43fc6f8b-9400-4d0d-b796-5f55ed519b98)

```
behavior {   
    layout {
        showActionBar false
    }
    quickSelect {
        activateOnAnyCharacter false
    }
keyBindings {
    "H" "core.move.left"
    "L" "core.move.right"
    "K" "core.move.up"
    "J" "core.move.down"
    "F1" "core.move"
    "F2" "core.rename"
    "Cmd+K" "core.actions"
    }
}
```

**Comment by vitusli** [comment]
1 minute later: after many months of not having succes seeing my own code in GitHub was the answer. When having it written like this it works!

![image](https://github.com/user-attachments/assets/8dc6d378-6ecc-4626-bb39-6968e2275fed)

**Comment by taliwalt** [comment]
Something I noticed was that when my configuration code was

`keyBindings {
"H" "core.move.left"
}`

I actually had to press `Shift+h` for the key binding to work. Changing my code to

`keyBindings {
"h" "core.move.left"
}`
Case Sensitive code solved my problems.
