### ISSUE TITLE
Preselect first option in popups

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#107]
on any popup the first option should be pre-selected by default so that hitting enter hits it
using the arrow key is not necessary in these scenarios

**Comment by monouser7dig** [comment]
I could not yet find a popup where this works?
And I noticed in the `Recently used` popup it would make more sense to select the second item/ leave out the first item at all cause that is just the current item (except if you implement global resents list)

**Comment by yanex** [comment]
@monouser7dig If you about Marta 0.5 EAP 1 I published [here](https://github.com/marta-file-manager/marta-issues/issues/221), it works for "smart menus" (e.g. "Favorites" or "Open with...").
It's actually a good idea to select the second item by default in "Recently used". I've created an issue for this (#222).

**Comment by monouser7dig** [comment]
If I open favorites nothing is pre-selected though? Is that an extra setting?

yes 0.5 😄 👍 I'm just writing a feedback to that issue as I'm typing

**Comment by yanex** [comment]
@monouser7dig It's disabled by default. Here is how you can enable it:

```
"behavior" {
    "menu": {
        "preselectFirstItem": true
    }
}
```

**Comment by monouser7dig** [comment]
my bad just noticed 😄 works!
