### ISSUE TITLE
Create directories recursively if the target directory does not exist yet (Copy/Move)

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#110]
when a file is moved/ copied one can not type in a path that does not yet exist

would be nice if that was possible and the folders would be created on demand 

thanks

**Comment by yanex** [comment]
Will be fixed in 0.5 (in which common file operations like file copying/deleting are entirely rewritten).

**Comment by monouser7dig** [comment]
looking forward to it, thanks !

**Comment by monouser7dig** [comment]
if you have `foo.go` and would ike to move it to `bar/foo.go` and autosuggestion might suggest target as `bar/bazz/foo.go`, if you delete `bazz` the cursor `bar/>>_<</foo.go` autocomplete does not work.

Would be good if it worked or is there another way of avoiding to retype the name of foo.go? **Maybe just add it to the list of auto suggestions so one can hit it with f>tab at the end?**

also, as far as I can see creating directories recursively does not work although it is mentioned in the 0.5 changelog #110
