### ISSUE TITLE
Date format should be customizable

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#12]
Date format in "Added", "Modified", "Created" columns should be customizable.

**Comment by yanex** [comment]
Also allow relative date (e.g. `Today in 9:00`).

**Comment by beeptech13** [comment]
How do you change the time format to 12 hour?  I tried changing it in the preferences right side but it has no effect.

**Comment by flav1000** [comment]
Hi @beeptech13, I tested it letter by letter, and the format string below will give you 12 hour format.

    timeFormat {
        normal "%l:%M%p"
    }

* That's a lowercase L`
