### ISSUE TITLE
Theme: no-title-bar option 

### ISSUE THREAD

**Issue by agustif** [marta-file-manager/marta-issues#121]
It seems marta is not trying to leverage the title bar for much use, so we could probably get rid of it like in atom as long as we integrate minimize-maximize-close on the UI itself...

**Comment by yanex** [comment]
Starting from Marta 0.5, the title bar contains a progress bar for asynchronous file operations, so it became mandatory.
I will close this issue as 'obsolete', but if still you have any suggestions, please file the new issue.
