### ISSUE TITLE
certificate invalid 

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#139]
https://marta.yanex.org

your certificate expired 4 days ago (at least that is what chrome says)

due to this, the update mechanism of Marta reports error and the website is not available (without ignoring the warning)

thanks for your great work, really good to see you doing continuous improvements! thanks

**Comment by yanex** [comment]
Fixed. Thank you!

**Comment by monouser7dig** [comment]
that was quick.... maybe even instant 👍 

app and website work again!

**Comment by monouser7dig** [comment]
`curl http://marta.yanex.org/`
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>
```

`curl https://marta.yanex.org/`
```html
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
```

**Comment by yanex** [comment]
Thanks!
