### ISSUE TITLE
Embedded terminal

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#142]

**Comment by monouser7dig** [comment]
could you give a brief description?
sounds interesting (wonder how this is "critical"?)

thanks

**Comment by yanex** [comment]
@monouser7dig It will look like this https://twitter.com/yanex_ru/status/904394250355449857 (But with better design).
It is critical just because the embedded terminal is deadly needed for any good file manager :)

**Comment by monouser7dig** [comment]
ok I see

OT:
[copy to android](https://twitter.com/yanex_ru/status/911729706449416194)
[snapdrop](https://github.com/RobinLinus/snapdrop)

**Comment by monouser7dig** [comment]
That was quick 

Just al thought:

Would it make sense to have a preference to automatically cd into the same directory as the current view/ selected tab is?

**Comment by yanex** [comment]
Yes, the terminal's current directory will be two-way synchronized with the file pane.

**Comment by monouser7dig** [comment]
Very nice 👍🏼
