### ISSUE TITLE
Support actionBar colors

### ISSUE THREAD

**Issue by gawashburn** [marta-file-manager/marta-issues#143]
It might be nice to be able to specify colors and icons for `actionBar`, so that the user could for example have them match their `touchBar` appearance.

**Comment by yanex** [comment]
Colors will be supported in 0.5.1.
I've made a separate issue for supporting icons, https://github.com/marta-file-manager/marta-issues/issues/347.

**Comment by yanex** [comment]
Syntax:

```
"setup": {
    "actionBar": [
        // Just an id (for backwards compatibility)
        "core.open.with",
        // An object with additional options
        {"id": "core.edit", "backgroundColor": "#ff0000", "textColor": "#ffffff"}
    ]
}
```
