### ISSUE TITLE
Contextual filtering modifier for Spotlight search

### ISSUE THREAD

**Issue by gawashburn** [marta-file-manager/marta-issues#144]
A really common use case for me is to want to search for a file with a given name or content in children of the current directory (so in Marta this would be the current pane), rather than everywhere Spotlight indexes.  

I'm not sure exactly the best way to expose this.  Perhaps with an additional prefix.  Something like `p:c:foo` to find files containing `foo` within children of the current pane, or `p:^:bar` to find files starting with `bar` inside the current pane or its children.

Of course, this assumes the Spotlight API makes it practical to implement.

**Comment by yanex** [comment]
Marta has a "Look up here" action (Cmd+Alt+P by default), and it seems that it does exactly what you want.

**Comment by gawashburn** [comment]
Ah, yes, that does exactly what I wanted, thanks!
