### ISSUE TITLE
Right click crashes marta

### ISSUE THREAD

**Issue by oomon** [marta-file-manager/marta-issues#148]
I am running Marta Version 0.4.3 (0.4.3) on OSX 10.11.6.  When right clicking on apparently any file or directory, marta closes.  It is possible to right click on the top and bottom portions of the marta window without any effect.  Right clicking on the the path displayed toward the top of the window works correctly and brings up a context menu.  It is also possible to right click on the '..' directory without marta closing.

**Comment by yanex** [comment]
Unfortunately, I can't reproduce this issue. Can you please attach the crash log?

**Comment by oomon** [comment]
Sure, see attached.
[marta-log.txt](https://github.com/marta-file-manager/marta-issues/files/1384217/marta-log.txt)
