### ISSUE TITLE
Volumes list (Alt+1) shows outdated/no longer mounted volumes

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#151]
Noticed that initially Marta showed me in Alt+1 two dmg images I had downloaded, so far so good.
Unmounted both dmg's in Finder, but Marta still showed them in Alt+1.
Restarted Marta, and the dmg volumes are still shown in Alt+1, bug?

**Comment by yanex** [comment]
I can't reproduce the bug :( The image list is not cached in Marta, so looks like the system still holds them.
Can you still see the unmounted images in "Disk Utility" system application? Also, can you delete (not just "Move to Trash") the unmounted `.dmg` files from Finder?

**Comment by warpkanal** [comment]
If it's not cached then maybe macOS is to blame.
Strange: finder does not show them, disk utility neither (also not on commandline via "diskutil list"), only marta:
![volume_list](https://user-images.githubusercontent.com/3669157/31576647-74d6df40-b0ff-11e7-86b2-592f87005d40.png)
I could delete both dmgs in finder. Still marta shows them (even after a new marta restart).
Strange, but anyway not a too big issue...

**Comment by yanex** [comment]
I'll investigate this anyway. Thanks for the report!

**Comment by yanex** [comment]
I changed the implementation the way it won't add the "hidden volumes". Hope this will fix this issue.
If the issue will still persist in 0.4.4, please let me know.
