### ISSUE TITLE
Option to remove ".."

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#152]
I use the keyboard to go up (key bound to left key, as I prefer left-right key navigation :) ).
Hence I do not use the ".." entry in the file list.
Would be cool if it could be optionally hidden.

**Comment by yanex** [comment]
In fact, you can do it. Set the `showGoUpDirectory` option to `false` in the configuration:

```
"behavior": {
    "table": {
        "showGoUpDirectory": false 
    }
}
```

Check the default configuration file (Cmd+Shift+P, "Open default configuration") for more configuration options.

**Comment by warpkanal** [comment]
Oh yeah, missed this one, thanks alot !
