### ISSUE TITLE
Queue/Async support for file operations

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#161]
For sure a bigger feature but in my opinion a core feature of a decent file manager:
- allow to put operations (e.g. long running copy operations or move between disks, etc) to background (either manually by a background button in the copy/... dialogs or generally per configuration)
- allow to queue operations (as at least on spindles parallel copy operations slow down i/o way too much), e.g. manually by a queue button in the copy/... dialogs or generally by limiting e.g. parallelism to 1 per configuration

**Comment by yanex** [comment]
Yes, asynchronous file operation API is a critical feature, and it definitely will be done in near future.
