### ISSUE TITLE
Support complex queries in Look up

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#163]
I understood that I can search e.g. for files having myquery in them with "fc:myquery". So I can obviously combine prefixes like f, @, c with an actual query like myquery.
Is it also possible to combine different prefixes with different queries?
E.g. I search (in a big hierarchy) for "xml" files containing the string "tika". On a first look "f@:xml,c@:tika" (and similar ones) did not work.

**Comment by yanex** [comment]
Complex queries are not supported yet. Thanks for the suggestion!

**Comment by monouser7dig** [comment]
:c does not work in 0.5 Look Up as far as I can tell. I have a .go file and cmd+alt+p using :c does not reveal anything, seems like it only matched directories.

**Comment by yanex** [comment]
@monouser7dig (This issue is not fixed yet. Complex queries are not supported in 0.5).
Maybe your file is not indexed by Spotlight yet. `c:` works for me (and there was no major changes in *Look up* since 0.4.7).

**Comment by monouser7dig** [comment]
my spotlight behaved flaky some time ago and I had to rebuild the index to fix it, maybe this is indeed the case.
