### ISSUE TITLE
Allow to drag-drop directories to Marta to open it

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#169]
Allow drag-drop to the dock icon, or to the title bar/tab bar.

**Comment by monouser7dig** [comment]
@yanex ot. ping:
marta displays a note saying it's outdated and a new version is available although it is not

**Comment by yanex** [comment]
@monouser7dig I've created an issue for it: https://github.com/marta-file-manager/marta-issues/issues/198.
