### ISSUE TITLE
Open Preferences in custom side-by-side editor

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#171]
There should be a side-by-side text editor with JSON highlighting (like in Sublime Text / Preferences / Settings).

**Comment by monouser7dig** [comment]
[solved](https://forum.sublimetext.com/t/side-by-side-view-from-command-line-mac/32660/5?u=14b56)

```bash
subl -n file1 && subl --command "set_layout {\"cells\": [[0, 0, 1, 1], [1, 0, 2, 1]], \"cols\": [0.0, 0.5, 1.0], \"rows\": [0.0, 1.0]}" && subl --command "focus_group {\"group\": 1}" && subl file2
```

**Comment by monouser7dig** [comment]
this is broken for me in 0.5 using Sublime 3160dev build

the command the sublime community provided and I mentioned above certainly still works so I think it's Martas fault.
