### ISSUE TITLE
etty: copy by selection, paste by right-click

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#174]
Ok, maybe this feature request is esoteric to non-linux users :)
But for me the (nearly) only reason why I prefer iTerm over Terminal is that I can configure to automatically have the mouse-selected text copied to the clipboard, and paste it directly with the right mouse key.
Anyways, etty really looks and feels very handy right from the start!!

**Comment by monouser7dig** [comment]
in the default configuration for etty I could not yet find it?

**Comment by warpkanal** [comment]
Me neither, maybe it's missing in the default configuration file?
Same for #174

**Comment by yanex** [comment]
@monouser7dig @warpkanal It is missing in 0.4.5, yes. Here is the configuration keys:

```json
"etty": {
    "pasteOnRightClick": true,
    "copyOnSelection": true
}
```

**Comment by warpkanal** [comment]
Thx!
