### ISSUE TITLE
etty: Remember size and state

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#175]
- [ ] remember size
- [ ] remember if etty was on or off last time
- [ ] remember scrolling pos in each terminal session when switching between dirs back and forth 

sweet release again!

**Comment by monouser7dig** [comment]
btw:
what are the five themes available for etty besides the default Pastel?

**Comment by yanex** [comment]
@monouser7dig See `/Applications/Marta.app/Contents/Resources/Themes`.

**Comment by monouser7dig** [comment]
the default is actually fine though

**Comment by yanex** [comment]
Moved "remember scrolling pos in each terminal session when switching between dirs back and forth" to its own issue: #362.
