### ISSUE TITLE
Blurred text in panel after PageDown or Down keys

### ISSUE THREAD

**Issue by ww7** [marta-file-manager/marta-issues#179]
Blurred text in panel after PageDown or Down keys 
But not after mouse scroll
![](https://i.imgur.com/PlZPlQA.png)

**Comment by yanex** [comment]
Unfortunately, I can't reproduce this behavior.
Does this issue still persist in 0.4.6?

**Comment by ww7** [comment]
In 4.6 still persist this issue.
This bug appear in directories where a lot of files, after passing "first portion" 
With mouse/touchpad scrolling font is normal.

**Comment by yanex** [comment]
@ww7 What kind of display do you use (Retina/non-retina)?

**Comment by yanex** [comment]
I was able to reproduce the issue (without Retina display).

![screen shot 2018-01-03 at 13 56 06](https://user-images.githubusercontent.com/95996/34509511-24794d2a-f08e-11e7-912a-4c0ccc1130b3.png)
![screen shot 2018-01-03 at 13 56 16](https://user-images.githubusercontent.com/95996/34509512-289101aa-f08e-11e7-8d59-ab9de3b0657b.png)
