### ISSUE TITLE
Crash while in background

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#182]
Nothing specifically done, just crashed while Marta was not the foreground app (and I added a file via some application into a directory which was in the open tab in marta).

[Marta_2017-11-02-122720.crash.zip](https://github.com/marta-file-manager/marta-issues/files/1437535/Marta_2017-11-02-122720.crash.zip)

**Comment by yanex** [comment]
Unfortunately, I can't reproduce this crash, and it's quite unclear why it happened.
Did it happen just once, or it is stable?

**Comment by warpkanal** [comment]
As far as I can tell, it happened only once. So not too dramatic, will send another crash report should it happen again.
