### ISSUE TITLE
Shortcut to sort by column

### ISSUE THREAD

**Issue by ronaldsuwandi** [marta-file-manager/marta-issues#186]
Would be great to have shortcut to sort by column :-)

**Comment by yanex** [comment]
Here is an "Ordering" action, you can launch it from the Action panel, or bind to a hotkey (action id: `core.ordering`).

**Comment by user3587412** [comment]
@ignaciovazquez It is possible to only use your keyboard: 
1. `cmd + shift + P` and select "Ordering...", or alternatively bind this action (`core.ordering`) to a keyboard shortcut 
2. press `space` to specify ascending/descending, and press `N`/`E`/`S`/`C`/`M`/`A` to sort by name, extension, size, created at, modifed at, or added at
