### ISSUE TITLE
Show free space in status bar/area

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#187]
Would be helpful if marta would show the free space of the current volume of the active tab in the status bar (especially helpful when having multiple disks...)

**Comment by monouser7dig** [comment]
Is there a setting to deactivate it?
I liked the clean look before and would find this only helpful on external volumes at all.

**Comment by yanex** [comment]
@monouser7dig Not yet. I've created an issue for it: https://github.com/marta-file-manager/marta-issues/issues/200.
