### ISSUE TITLE
Separate key bindings for opening a folder and opening a file?

### ISSUE THREAD

**Issue by rltbennett** [marta-file-manager/marta-issues#188]
It would be nice to have separate keybindings for drilling down into a folder (the opposite of the "go up" command) and opening a file. This way, it would be impossible to avoid accidentally opening files when attempting to drill down into a folder. In my ideal world, both Enter and Right-Arrow open a folder, while only Enter opens a file.

**Comment by yanex** [comment]
The new action will be available with id `core.open.directory`.

**Comment by rltbennett** [comment]
Thanks!
