### ISSUE TITLE
Live reload keybinding settings

### ISSUE THREAD

**Issue by rltbennett** [marta-file-manager/marta-issues#189]
Would be nice if Marta reloaded the settings file whenever it was edited. Currently, you must restart Marta for changes to take effect.

**Comment by yanex** [comment]
Marta supports hot reloading for settings from the first release.
Does the hot reloading not work for you at all, or the problem is with some particular settings?

**Comment by rltbennett** [comment]
Seems to not work for me at all. At least, with all settings I've edited.

**Comment by yanex** [comment]
Unfortunately, I can't reproduce this issue.

Can you provide some more details about what Marta/macOS versions do you use?
Also, have you installed Marta to Applications folder?

**Comment by rltbennett** [comment]
Sorry, looks like most settings do live reload. Just not the ones involving keybindings.

**Comment by yanex** [comment]
Yes, key binding reloading is not supported yet.
