### ISSUE TITLE
Quick Select: Highlight matched items

### ISSUE THREAD

**Issue by ronaldsuwandi** [marta-file-manager/marta-issues#191]
At times I typed something in Marta and I didn't know I'm in the middle of quickSelect feature until I hit escape button. I think good reference to use is how Nimble Commander does it

<img width="614" alt="screenshot 2017-11-15 09 20 17" src="https://user-images.githubusercontent.com/4120788/32816371-4dc3477e-c9f3-11e7-89bc-166ad64c9fb0.png">
Note that the typed text is at the top and there is underline in the filtered result

<img width="627" alt="screenshot 2017-11-15 09 20 24" src="https://user-images.githubusercontent.com/4120788/32816372-4e0db228-c9f3-11e7-823a-1b0a98427172.png">
In Marta the typed text is all the way at the bottom - making it easy to miss

Another recommendation is perhaps turn on `filterMatchedItems: true` by default

**Comment by yanex** [comment]
I personally don't like `filterMatchedItems`, the blinking file list view is a bit irritating. This feature was implemented as a user request.
I also don't think that moving the filter text to the top will change anything. I think it's just a matter of habit. And there is no free space on the top anyway.

But the matching result highlighting really needs to be implemented.

**Comment by ronaldsuwandi** [comment]
True, blinking can be annoying. Actually now that I think about it, essentially this boils down to result highlighting. Once it's implemented, it won't be a problem anymore :-)

**Comment by ronaldsuwandi** [comment]
> I also don't think that moving the filter text to the top will change anything. I think it's just a matter of habit. And there is no free space on the top anyway.

Not saying that Marta must copy NC behaviour but I noticed that in NC it swaps the path with the currently searched item which I found pretty neat and make it more obvious that it's on filtering mode
