### ISSUE TITLE
Terminal ctrl+c key combination not working

### ISSUE THREAD

**Issue by pelemarse** [marta-file-manager/marta-issues#193]
Marta version: Version 0.4.4 (0.4.4)
MacOS version: High Sierra 10.13.1 (17B48)

**Comment by yanex** [comment]
Unfortunately, I can't reproduce this issue. Tried with:

1. `cat /dev/urandom > /dev/null`
2. `^C`.

Can you please share some more details about your configuration (shell, process being launched, etc.)? Please also update to Marta 0.4.5 and check if the bug is fixed there.

**Comment by yanex** [comment]
I still can't reproduce this issue.
If you still have this, please file the new issue (and it would be nice if you mention #193).
