### ISSUE TITLE
App icon is missing after upgrading to 0.4.5

### ISSUE THREAD

**Issue by ronaldsuwandi** [marta-file-manager/marta-issues#202]
Happened after I do an in-place upgrade (check for updates->update)

![image](https://user-images.githubusercontent.com/4120788/33587398-f49a5fe6-d9a8-11e7-8fcb-8644df299d04.png)

**Comment by yanex** [comment]
Did you try to restart macOS? I had issues like yours before with different apps, and all of them disappeared after the restart.

**Comment by yanex** [comment]
Unfortunately, I can't reproduce this issue. If the bug still remains, please file the new issue instead.
