### ISSUE TITLE
Do not display the "This version of Marta is obsolete" alert

### ISSUE THREAD

**Issue by udalov** [marta-file-manager/marta-issues#203]
I'm opening Marta and seeing this:
<img width="427" alt="screen shot 2017-12-07 at 20 15 37" src="https://user-images.githubusercontent.com/292714/33733882-7a3420cc-db8b-11e7-8b8d-c6ac30703440.png">

After I click "Close", I see this:
<img width="1210" alt="screen shot 2017-12-07 at 20 16 29" src="https://user-images.githubusercontent.com/292714/33733914-8d45f186-db8b-11e7-9ae2-3ac15847a220.png">

... which probably means the first alert is not needed? Since I can "Install Update" in the second one?

**Comment by yanex** [comment]
The entire obsolete version check will be removed in 0.5.1 so the "This version of Marta is obsolete" alert definitely won't appear. :)
