### ISSUE TITLE
Look up: Add documentation

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#215]
personally I can not tell the difference between `look up` and `go to path` 
maybe it would make sense to join them or give them more explicit names?

`look up` has a nice/ integrated UI though

**Comment by yanex** [comment]
Well, it's not easy to figure out you can paste absolute paths to "Look up". "Go to path" is simpler and provides a functionality many users got used to.
Also, you can use Go to path to copy the current directory path (as an alternative to "Copy current directory path" action).

**Comment by yanex** [comment]
But you are right, documentation has to be updated to reflect changes in Look up.

**Comment by monouser7dig** [comment]
maybe `go to path`could be modified to allow absolute paths (after all an absolute path still is a path)? And `look up` would not be needed anymore

>  a functionality many users got used to.

is this meant as an argument for separating `look up` and `go to path`? If so, I do not see how those users would be badly affected by an enhancement of `go to path` which incorporates `look up`
(or maybe there are other differences to `look up`)

> Also, you can use `Go to path` to copy the current directory path (as an alternative to "Copy current directory path" action).

seems like a rather weird [workflow](https://imgs.xkcd.com/comics/workflow_2x.png) to me and would still not contradict integrating `look up` into `go to path`?

**Comment by yanex** [comment]
"Go to path" supports only absolute paths (an absolute path is a path starting with `/` or `~`). Are you about relative paths?

The primary goal of "Go to path" is to open the path, while "Look up" is a tool for quick searching files using common predicates, like the part of its name, or its title. Starting from 0.4.6, "Look up" supports absolute paths, but you can consider it as an another kind of predicate.
⌘G, ⌘C can be actually easier than remembering an another hotkey for copying current directory path.

Also, "Go to path" can support connecting to non-local resources (e.g. SMB, SFTP etc.) in future, so leaving this functionality for now is rather a good thing.

**Comment by monouser7dig** [comment]
I think I understand now and documenting instead of merging makes sense.
