### ISSUE TITLE
Quick Select: Do not filter out elements on "/" or "\" query

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#218]

**Comment by monouser7dig** [comment]
I have `"filterMatchedItems": true,` and after hitting `/` and typing, it does not filter.
Maybe I missed a setting again but... 😄  (5.0 beta1)

**Comment by yanex** [comment]
@monouser7dig I just checked, and it looks like it works for me.
Do you say Quick Select does not work for you anymore when `filterMatchedItems` is `true`?

**Comment by monouser7dig** [comment]
It was a stupid mistake on my side, all works fine. I'll grab some food and take more time 👍
