### ISSUE TITLE
Show progress indicator when enter directories on slow external drives

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#220]
After recently browsing some slow external harddrive with lots of folders, I missed some visual indicator (e.g. a spinner in the status bar) that would indicate whether e.g. I really entered a folder and just need to wait for marta to list all children (so the spinner would be spinning) or whether maybe I mistyped or did not press some key correctly (and thus the spinner would be invisible) and therefore nothing is happening.

**Comment by monouser7dig** [comment]
now one can copy multiple folders at once, it would also help to visually indicate the folders that have operations pending or maybe even show the progress of the respective operation
