### ISSUE TITLE
Async: Queue popup should be styled

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#227]
Now it has the default system background. For Kon it's too bright.

**Comment by monouser7dig** [comment]
is this actually improved in the second beta? It's still grey.

**Comment by yanex** [comment]
@monouser7dig Now you can choose the `controlStyle`. By default, the style defined in the current theme is used (and it's `default` for *Kon*), but you can manually specify the `dark` style in preferences.

**Comment by monouser7dig** [comment]
yes this works well, maybe this could be made the default if a dark theme is selected
