### ISSUE TITLE
Marta header strangely resized

### ISSUE THREAD

**Issue by warpkanal** [marta-file-manager/marta-issues#232]
After switching to external monitor and back and again to another monitor, marta strangely resized its header:
![marta 2018-01-10 13-52-30](https://user-images.githubusercontent.com/3669157/34773931-b8811d02-f60d-11e7-94e9-c501ef8e7aba.png)

Resizing the marta window doesn't change this strange header, restarting marta however does and everything is fine again, so this is more a minor bug.

**Comment by yanex** [comment]
Can you reproduce it, or it happened just once?

**Comment by warpkanal** [comment]
Happened twice but cannot reproduce for now...

**Comment by yanex** [comment]
For now, I will close the issue with "Can not reproduce". If this will happen for you (or someone else) again, please leave a comment, or file a separate issue.

**Comment by agalitsyn** [comment]
@yanex I constantly got this error, it prevents me to launch more that 1 instance of Marta and use it on different workspaces, completely substitutes Finder. 

![image](https://user-images.githubusercontent.com/1642205/187205970-5aed206e-1551-48c2-a2cf-bfcac0cb0254.png)


For me it reproduces when I plug in external monitor and unplug it later.

**Comment by beho** [comment]
Hi, I'm getting in this state reliably since I started using [Amethyst](https://ianyh.com/amethyst/). It's sort of a tiling window manager. It's automatic positioning/resizing capabilities cause this to Marta quite quickly.

It might be a way to reproduce this behaviour.

**Comment by pax** [comment]
I can confirm this still happens after the 0.8.2 update

Using an external display - besides the default one.

Sonoma 14.6.1 (23G93) - MBP 14' 2021 / M1 Pro

**Comment by ngocphamm** [comment]
Duplicate of https://github.com/marta-file-manager/marta-issues/issues/1067
