### ISSUE TITLE
Add JB_team badge 

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#235]
![](https://img.shields.io/badge/project-team-brightgreen.svg?style=flat-square&label=&colorA=3c3c3c&colorB=15d2b1&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB3aWR0aD0iMTRweCIgaGVpZ2h0PSIxNHB4IiB2aWV3Qm94PSIwIDAgMTQgMTQiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDE0IDE0IiB4bWw6c3BhY2U9InByZXNlcnZlIj48cmVjdCB4PSIxIiB5PSIxMiIgZmlsbD0iI0ZGRkZGRiIgd2lkdGg9IjciIGhlaWdodD0iMSIvPjxwYXRoIGZpbGw9IiNGRkZGRkYiIGQ9Ik0wLjMsNy4zbDEtMS4xYzAuNCwwLjUsMC44LDAuNywxLjMsMC43YzAuNiwwLDEtMC40LDEtMS4yVjFoMS42djQuN2MwLDAuOS0wLjIsMS41LTAuNywxLjlDNC4xLDguMSwzLjQsOC40LDIuNiw4LjRDMS41LDguNCwwLjgsNy45LDAuMyw3LjN6Ii8%2BPHBhdGggZmlsbD0iI0ZGRkZGRiIgZD0iTTYuOCwxaDMuNGMwLjgsMCwxLjUsMC4yLDEuOSwwLjZjMC4zLDAuMywwLjUsMC43LDAuNSwxLjJsMCwwYzAsMC44LTAuNCwxLjMtMSwxLjZDMTIuNSw0LjgsMTMsNS4zLDEzLDYuMmwwLDBjMCwxLjMtMS4xLDItMi43LDJINi44VjF6IE0xMSwzLjFjMC0wLjUtMC40LTAuNy0xLTAuN0g4LjR2MS41aDEuNUMxMC42LDMuOSwxMSwzLjcsMTEsMy4xTDExLDMuMXogTTEwLjIsNS4zSDguNHYxLjZoMS45YzAuNywwLDEuMS0wLjIsMS4xLTAuOGwwLDBDMTEuNCw1LjYsMTEuMSw1LjMsMTAuMiw1LjN6Ii8%2BPHJlY3QgeD0iMSIgeT0iMTIiIGZpbGw9IiNGRkZGRkYiIHdpZHRoPSI3IiBoZWlnaHQ9IjEiLz48L3N2Zz4%3D)

[JB_TEAM](https://confluence.jetbrains.com/display/ALL/JetBrains+on+GitHub)

> Team projects are those that were created by JetBrains employees. These projects include 20% projects and internal hackathons, those that support the product development process, or those that benefit the JetBrains developer community.

I think this project is:
- those that support the product development process
- or those that benefit the JetBrains developer community

this would ["solve"](https://github.com/marta-file-manager/marta-issues/issues/194#issuecomment-352363612)
> Trust is a huge point, but I never saw people who check the app source code before using it. There are lots of closed-source software for macOS and looks like nobody actually bothers about it.

I certainly have more trust in a JetBrains developer managing my files than some github user with an alpha-stage project (paraphrasing a bit)

**Comment by yanex** [comment]
Well, Marta is neither a 20% project (I make it in my spare time and don't receive any money from JetBrains), nor it has any integrations with the existing JetBrains products (like [teamcity-rest-client](https://github.com/JetBrains/teamcity-rest-client) which can be considered as a logical part of TeamCity). So I chose not to add the badge, at least for now :)
