### ISSUE TITLE
Please add support for browsing tarballs

### ISSUE THREAD

**Issue by rbZend** [marta-file-manager/marta-issues#238]
Browsing tarballs is the only critically missing functionality for me. Of course, I mean primarily TAR.GZ.

**Comment by monouser7dig** [comment]
duplicate of #237 ?

**Comment by rbZend** [comment]
Just TAR and TAR.BZ would be nice, too. But you're right, seems to be a duplicate.

**Comment by yanex** [comment]
Closed as duplicate.
