### ISSUE TITLE
Docs: Support Visual Studio Code Insiders as text editor

### ISSUE THREAD

**Issue by Gr1N** [marta-file-manager/marta-issues#240]
Hello!

Thanks for an awesome product you created! I really like this project, but for now I can't setup my editor as `textEditor` in Marta. 

You already support Visual Studio Code as option, but not Insiders build. Is it possible to use Insiders build as `textEditor` in Marta?

Best regards

**Comment by yanex** [comment]
Hello, @Gr1N!
I've tried VS Code Insider build and looks like it works. Just change the configuration value for `editor` to `Visual Studio Code - Insiders`:

```
"environment": {
    "textEditor": "Visual Studio Code - Insiders"
}
```

Note that you may be need to change the name if you renamed the VS Code application inside your `/Applications` dir.

**Comment by Gr1N** [comment]
@yanex thank you!

Now I understand that I can define any `textEditor` using it's name in `Applications` or I'm wrong? If it's true maybe someone need to describe this in [docs](https://marta.yanex.org/docs#edit)?

**Comment by yanex** [comment]
@Gr1N Yes, it should work with almost with any text editor.
Yes, I will update the documentation, thanks!.

**Comment by crispinb** [comment]
Doesn't work with Emacs (GUI Emacs.app in /Applications).  Prefs insist on opening in TextEdit.

Wouldn't it be more flexible to have the textEditor value as a path rather than an app name? Or if an editor name is preferred for the common cases, have an alternative textEditorPath key?
