### ISSUE TITLE
Hide the "Move to Trash" confirm dialog

### ISSUE THREAD

**Issue by lep2015** [marta-file-manager/marta-issues#243]
when i want to delete file ,a confirm dialog appear, can this be config?
I  want to config the dialog show or not
![image](https://user-images.githubusercontent.com/11475497/35957334-08fb4580-0cd6-11e8-9a32-e3cdbcf3e942.png)

**Comment by yanex** [comment]
In fact you can:

```
"behavior": {
    "actions": {
        "core.trash.confirm": false
    }
}
```

See the default configuration file (Cmd+Shift+P, "Open default configuration") for more configuration options.

**Comment by lep2015** [comment]
oh, thanks!!!
i am careless, I will read the doc carefully next time
😄
