### ISSUE TITLE
Etty: Alt+Left/Right should put caret to the previous/next word

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#296]

**Comment by monouser7dig** [comment]
cmd left/right to the beginning/end of line?

**Comment by yanex** [comment]
@monouser7dig There are already Ctrl+A and Ctrl+E for that (and they're terminal-agnostic).

**Comment by monouser7dig** [comment]
yes but if it does not interfere I think it's even easier 
(I do not always remember ctrl a ctrl e although I use the terminal quite a bit) but if it'd be a hassle to implement it's sure ok to not have it.

**Comment by yanex** [comment]
How about Cmd+Shift+Left/Right?

**Comment by monouser7dig** [comment]
I just use cmd shift/left in sublime and everywhere in macOS so if it's different I might as well start remembering ctrl e ctrl a I guess.
Can't really say if that is the general case or just me 😆

**Comment by yanex** [comment]
@monouser7dig Ah, you're right. Didn't realize I do this as well 😆 
Then Cmd+Left/Right makes sense 💯
