### ISSUE TITLE
Graceful fallback if the Trash is not supported

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#3]
When deleting from a volume that doesn't support "Trash", the delete does not succeed. There should be some non-trash full delete fallback for these cases.

<img width="424" alt="2017-04-06 at 12 21 48 pm" src="https://cloud.githubusercontent.com/assets/95996/24888181/100c7156-1e6a-11e7-811a-9213d12770e7.png">

**Comment by VKondakoff** [comment]
Unfortunately, this is still not fixed in Marta 0.7. Please, move this issue higher in your development list.
Thank you!
