### ISSUE TITLE
Package files should not be treated as directories when sorting files

### ISSUE THREAD

**Issue by thousandsofthem** [marta-file-manager/marta-issues#309]
Are there any way to always show directories on top?

**Comment by yanex** [comment]
@thousandsofthem You mean, in the title area?

**Comment by thousandsofthem** [comment]
Nope, i mean ordering in the primary files/folders area
```
[..]
folder1
folder2
file 1
file2
```

**Comment by yanex** [comment]
@thousandsofthem Hm, it's how it should work by default. Could you please take a screenshot?

**Comment by thousandsofthem** [comment]
![screen shot 2018-03-31 at 22 33 53](https://user-images.githubusercontent.com/736279/38166872-adf4d170-3533-11e8-8882-400a55674b96.png)

**Comment by yanex** [comment]
I wonder if Marta thinks of docx, pages and app files as directories rather than the ordinary files.
I will check it, thanks!

**Comment by thousandsofthem** [comment]
Maybe having .app/.pages thing "poisoned" sorting logic somehow - there are at least 3 regular folders as well.
Did a quick check - sorting changed after moving `Contract_translated.pages` out

**Comment by user3587412** [comment]
Is there a way to *not* show the directories on top, like the default macOS Finder?

**Comment by yanex** [comment]
@user3587412 Not yet. Please submit this as an another feature request.
