### ISSUE TITLE
Search ignores content within /<UserName>/Library

### ISSUE THREAD

**Issue by CandyFace** [marta-file-manager/marta-issues#318]
When I search for folders using "global look up" (cmd+P) within my /\<Username\>/Library folder, nothing appears. Is this a bug or an expected behaviour?

I looked through the docs but found nothing mentioning that the look up should be limited to certain folders.

I'm on Mac OS 10.12.6

**Comment by yanex** [comment]
*Look up* is based on the Spotlight functionality, and it looks like Spotlight doesn't index files in `~/Library`. I don't know a work-around for this right now.

**Comment by yanex** [comment]
UPD: [People say](https://discussions.apple.com/thread/2084903) the `Library` folder is actually indexed but excluded from the search results by default. I will investigate what can be done here.

**Comment by CandyFace** [comment]
Yeah that seems to be the case. 
https://apple.stackexchange.com/questions/232404/show-library-folder-and-subfolders-in-spotlight-search?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

You specifically have to search for system files and it still only shows in folder, not in spotlight.

**Comment by yanex** [comment]
UPD: Looks like there's no public API for that. Finder uses some internal methods to search for "non-user" and "non-Finder" files.
I'll resume the research later (also there's a chance someone else will find a way to do this).
Some words to start: `RawQueryDict`, `FinderFilesOnly`, `UserFilesOnly`, also `TSliceInterpreter` class.

**Comment by yanex** [comment]
UPD: It seems Spotlight indexes the Library folder, at least on Big Sur. However, Marta explicitly excluded filtered results inside it. I removed the filter so it should work properly in 0.8.1. At least now I can find folders inside `~/Library` now.
