### ISSUE TITLE
Action: Clear terminal buffer

### ISSUE THREAD

**Issue by jandillmann** [marta-file-manager/marta-issues#329]
iTerm has this really convenient shortcut to clear the terminal buffer (`cmd+K`).
I really like working with Marta and the terminal window at the bottom, and this feature would really be the icing on the cake.

**Comment by monouser7dig** [comment]
you can use 

`alias clear="clear && printf '\e[3J'"` works for me so far although I am not sure clearing the buffer is exactly what it does but the effect should be the same.

**Comment by jandillmann** [comment]
yes, of course I can type `clear` – but I'm so used to `cmd+K` that I find myself constantly trying to use this shortcut :)

**Comment by monouser7dig** [comment]
it's actually different from just clear in that it also disables scrolling back, I find that very convenient.
