### ISSUE TITLE
File selection resets whenever a moving operation completes

### ISSUE THREAD

**Issue by user3587412** [marta-file-manager/marta-issues#332]
Whenever a moving operation completes, the quick selection you had on both panels reset (I am assuming it is because marta refreshes both panes whenever a move operation completes).

For example, if you move 10 files that takes 2 seconds to complete for each file (a total of 20 seconds), and try to select files in between, your selection will be reset 10 times because it resets whenever a moving operation completes.

**Comment by user3587412** [comment]
Similarly, if you set `filterMatchedItems` to `true` for `quickSelect`, the filtering resets whenever a move operation completes

**Comment by yanex** [comment]
In 0.5.1 selection will be correctly restored after the list refreshing so this problem should go away.
