### ISSUE TITLE
Feature Request: Config file location

### ISSUE THREAD

**Issue by nicholasjackson** [marta-file-manager/marta-issues#333]
Hi,

I am loving Marta, it is now my goto tool for working with files on my Mac.  As a heavy Vim and Tmux user the ability to configure keybindings to use Vim keys is nothing short of a revolution in my day to day workflows.

I was wondering if it is possible to leverage a standard config directories for unix for example ~/.config/org.yanex.marta instead of ~/Application Support/org.yanex.marta.  I generally version my dot files in Github, for the moment I have symlinked from ~/.config to ~/Library/Application Support however when using the actions "Open configuration directory" Marta will not follow the symlink.

Kind regards,

Nic

**Comment by yanex** [comment]
The `Application Support` is the default location for all macOS applications.
Will the symlink resolution in "Open configuration directory" action be sufficient for you?

**Comment by nicholasjackson** [comment]
Yeah that would be awesome

**Comment by yanex** [comment]
Seems like this is already supported in Marta 0.6.2.
I will close this issue as obsolete. If you find out it still doesn't work, please feel to comment and/or reopen the feature request.
