### ISSUE TITLE
Open Preferences in custom side-by-side editor (again)

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#343]
[see](https://github.com/marta-file-manager/marta-issues/issues/171#issuecomment-377636174)

> this is broken for me in 0.5 using Sublime 3160dev build
> the command the sublime community provided and I mentioned above certainly still works so I think it's Martas fault.

**Comment by yanex** [comment]
Side-by-side was disabled because the overall user experience was not good enough (two tabs are closed separately, and the "default configuration" tab asks if the file should be saved).
You can enable it manually:

```
"behavior": {
    "doublePaneConfigurationInSublime": true
}
```

As a long-term solution, the custom side-by-side editor will be provided.

**Comment by monouser7dig** [comment]
allright, astonishing how you manage all those preferences 😃 
I noticed it was a little weird, as you describe but still better than opening two panes by hand IMO.
