### ISSUE TITLE
etty: Unable to type a pipe

### ISSUE THREAD

**Issue by sceptiq** [marta-file-manager/marta-issues#357]
Hey, 

typing a pipe in the etty doesnt bring up a pipe but jumps to the beginning of the line.

**Comment by yanex** [comment]
Can't reproduce.
What keys do you press to type a pipe symbol?

**Comment by sceptiq** [comment]
Hey! 

```option+7``` is there another way? :)

(https://www.dropbox.com/s/njaoiebfx125z3v/martasPipe.mov?dl=0)

**Comment by yanex** [comment]
Did you set a custom hotkey for the `core.show.operation.queue` action?

**Comment by yanex** [comment]
Are you about the `|` symbol?
There's a `\` key on my keyboard, and I just press it with `Shift`.
What keyboard layout do you have?

**Comment by sceptiq** [comment]
jeah :) 

```alt+7 => |```

German (qwertz) keyboard.
