### ISSUE TITLE
0.5.1 release?

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#361]
I appreciate the time you put into 0.5.1, trying to put all those fixes in, but maybe a release could be tagged nevertheless?

**Comment by yanex** [comment]
While working on features for 0.5.1, I decided Marta needs a major refactoring to fix long-lasting issues, as well as to increase maintainability and testability. The refactoring is almost done, I hope it will end this week.
Although improving code quality is not something that users may feel directly, it's definitely needed in the long run. The alternative is to put ad-hoc patches here and there, but this only leads to unstable software that eventually requires a complete rewrite to fix problems.

**Comment by monouser7dig** [comment]
Yes definitely true, thanks for the update on the status quo, take your time 👍
