### ISSUE TITLE
"Open Marta application bundle" action not shown in Action Search results

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#365]
Steps:
1. Press Cmd+Shift+P to open Action Search.
2. Start typing something like "Marta" or "bundle".

Result:
"Open Marta application bundle" action not shown in results.
![image](https://user-images.githubusercontent.com/26354715/41649829-2c9c1854-7485-11e8-86c9-537e34716771.png)
Search works fine for other actions I have tried.

**Comment by yanex** [comment]
Where did you find about the "Open Marta application bundle" action?
Now it's internal, and I plan to remove it completely.

**Comment by krupenja** [comment]
Ok, thank you for clarifying this.
If you open Actions without typing anything and scroll down, you can see it in the list:

![image](https://user-images.githubusercontent.com/26354715/41811561-ad45dfe8-771a-11e8-9e06-4d5bcf746d41.png)
