### ISSUE TITLE
Etty: sending interrupt using Ctrl+C does not work

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#368]
Steps:
1. Open Etty terminal in Marta.
2. Type in a command which takes long to execute, e.g. `find /  -iname "*.mp3"`
3. Press Ctrl+C to send an interrupt.

Result:
Nothing happens. Checked that interrupts are send OK in macOS Terminal.

**Comment by krupenja** [comment]
OK, I have taken a look also at the closed issues and looks like it has already been reported before in #193. So based on a comment there, providing some more info:

1. In addition to the command I specified above, I have also tried `cat /dev/urandom > /dev/null` and get the same result: interrupt is not sent.
2. My shell is bash, macOS is recently installed.
3. Contents of my `.bash_profile`:
```bash
# Adding ~/bin to PATH
export PATH=$PATH:~/bin

# Colors and tweaks for bash prompt
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "

# Command line and ls colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# ls tweaks
alias ls='ls -GFh'
```
4. macOS is 10.13.5, Marta is 0.5.

Please let me know what other info you need to investigate.

**Comment by yanex** [comment]
Reproduces with bash and sh, not with zsh.
Investigating.
