### ISSUE TITLE
Marta does not respect national date format with default settings

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#369]
Steps:
1. Open macOS Language & Region settings and make sure region with dd/mm/yyyy date format is selected (I have tried Estonia, Italy and Russia).
![image](https://user-images.githubusercontent.com/26354715/41811706-52ed55c8-771d-11e8-9049-974ff06e4c5f.png)
2. Reboot macOs.
3. Make sure that date format is set to the default setting in user conf.json (i.e. `"dateFormat": "%x %X"`) *or* this setting is not in conf.json altogether so Marta uses defaults.
4. Open Marta.

Result:
The date format is in mm/dd/yyyy. Notice that on the screenshot 06 (June) comes before dates.
![image](https://user-images.githubusercontent.com/26354715/41811695-07b7f716-771d-11e8-92e1-ae5aade70c27.png)

Workaround:
Use `"dateFormat": "%d/%m/%y %X"` in conf.json to get the correct dd/mm/yyyy format.

**Comment by yanex** [comment]
Looks like macOS forces the ISO date format regardless of the current locale settings.
I think I will change the default format to `%D %R` as it's the most common used.
