### ISSUE TITLE
selection still active after entering folder.

### ISSUE THREAD

**Issue by sceptiq** [marta-file-manager/marta-issues#370]
```Version 0.5.1 (0.5.1)```

i like to enter a folder called ```src```:

i type ```src``` and all folders get selected that start with src. In this case there is only the one im looking for.
i press return to enter the selected folder. Now im in the folder, but i cant use the arrow keys to navigate cause ```selection``` is still active i have to press ```esc``` to reset the pre selected search.

**Comment by warpkanal** [comment]
Interesting, in my case I can't even reset the selection with `esc` (there happens nothing except displaying "Deselect all cannot be run in this context" when I hit `esc` the second time. Makes quickselect unfortunately broken for me.

**Comment by yanex** [comment]
Ah. This is bad.
The bugfix release will be available today.

**Comment by yanex** [comment]
@sceptiq @warpkanal Please check if this build works for you.
[Marta-0.5.2.zip](https://github.com/marta-file-manager/marta-issues/files/2139334/Marta-0.5.2.zip)

**Comment by warpkanal** [comment]
Works perfectly fine for me, thanks!

**Comment by yanex** [comment]
Fixed in 0.5.2, please update to it.
