### ISSUE TITLE
File list does not update when there's a new file

### ISSUE THREAD

**Issue by user3587412** [marta-file-manager/marta-issues#372]
Marta does not detect and refresh the file list when there is a new file added to the directory. 

Marta version: 0.5.2, although I think I saw the same issue since 0.5.1

**Comment by krupenja** [comment]
Confirm that I also have this with Marta 0.5.2.

**Comment by yanex** [comment]
Duplicate of https://github.com/marta-file-manager/marta-issues/issues/380, will be fixed in 0.5.3.
