### ISSUE TITLE
No progress indicator for Duplicate action

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#374]
Steps:
1. Try using a Duplicate action on a large file or on a folder(s) containing large files.

Result:
Confusingly, there is no indication that a file is being duplicated and duplicate file/folder is not shown immediately (while duplicating). This could give an impression that nothing happens and Duplicate action failed. Some progress indicator like the one for file/folder copying would be very helpful.

**Comment by yanex** [comment]
Can't reproduce. A progress indicator is shown for me (it's on the top-right corner).
Do the file successfully copied in your case?

**Comment by krupenja** [comment]
OK, now I am unable to reproduce this myself after trying out with different files/folders. So we can close for now, at least until the problem resurfaces.
