### ISSUE TITLE
Problem with keyBindings

### ISSUE THREAD

**Issue by sedovalx** [marta-file-manager/marta-issues#376]
I have the next config for my key bindings:
```
 "keyBindings": {
        "core.open": ["Right", "Return"],
        "core.go.up": ["Left", "Backspace"],
  ...
}
```
It worked like charm until I upgraded from 0.5.0. Now, nothing happens when I use left/right arrows in the file pane. Though, "Cmd+Right"/"Cmd+Left" are working. Is it forbidden to use arrows for the navigation now?

**Comment by yanex** [comment]
Now there are "Move left" and "Move right" actions. Both are *core* actions, and they unconditionally override others. Unset the hotkeys for them to get the behavior you want:

```
"core.move.left": [],
"core.move.right": []
```

**Comment by sedovalx** [comment]
Thank you! 

p.s.: also, would be great to have a brief description of all default actions in the https://marta.yanex.org/docs#actions section of the documentation.
