### ISSUE TITLE
Filter lines instead of highlighting by typing

### ISSUE THREAD

**Issue by KreiDer** [marta-file-manager/marta-issues#377]
Hi @yanex 
I'm proposed to add next behavior:

**Current behavior:**
Once we type any word we see highlighting of them and can navigate as well.

**New behavior:**
Filter and show only lines that match the criteria. 

PS: I'm experimenting with different file manages and see that "Nimble Commander" have such behavior (See example gif https://www.dropbox.com/s/bw4ldwamsozrdvn/filter%20typing.gif?dl=0). 

Thanks,
Yauheni

**Comment by monouser7dig** [comment]
There should be an option in the config to do just that if I understand you correctly

**Comment by warpkanal** [comment]
It should be behavior -> quickSelect -> filterMatchedItems -> true.
Check the global options (Cmd+Shift+P "Open default configuration").

**Comment by KreiDer** [comment]
@warpkanal Many thanks, I like that file manager more and more )
