### ISSUE TITLE
Unable to map "core.new.file": ["Cmd+N"]

### ISSUE THREAD

**Issue by KreiDer** [marta-file-manager/marta-issues#383]
Once I've tried to map the shortcut to create new file: 
`"core.new.file": ["Cmd+N"]`
it still open new window although  `"core.new.window": []` is empty.

**Comment by yanex** [comment]
Cmd+N is a system-global shortcut (like `Cmd+Q` or `Cmd+,`). Right now it's impossible to override it, but I'd leave this open in case if this will become significantly easier to implement after some refactoring.

**Comment by yanex** [comment]
Apparently, Marta 0.8 fixes this. (#688)
