### ISSUE TITLE
Rename "Copy" to "Copy to…", add a silent "Copy" command

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#387]
The silent version won't ask about the target path. It will just copy the source to the inactive pane.
Key bindings won't change, F5 will still run "Copy to…" with a path dialog.

**Comment by achekulaev** [comment]
Hi @yanex 
Could you say how the silent copy command is called internally? `core.copy...`? I would like to assign it to hotkey/actionbar. Also it does not seem to be enabled in the file menu for me. The item is disabled.

**Comment by M0rtenB** [comment]
I'd love to know as well.
