### ISSUE TITLE
When entering  a directory the first file entry is selected

### ISSUE THREAD

**Issue by inikolaev** [marta-file-manager/marta-issues#408]
I'm not sure is that's by design but coming from Far or NC or MC this looks weird: whenever I enter a directory the first file entry is being selected. I would expect that the `..` entry is selected which allows to exit directory right away. Also Finder doesn't select the first entry whenever you open a directly - so such behavior seems to be consistent across many file managers.

**Comment by dieterguendisch** [comment]
When using left, right (#409) and disabling the `..` entry, it's super efficient to have the first entry selected :)
You can disable the `..`folder with
```
"table": {
    "showGoUpDirectory": false 
},
```

**Comment by yanex** [comment]
@inikolaev You can disable this behavior by setting the "selectGoUpDirectoryOnEnter" configuration value to `true`:

```
"behavior": {
    "table": {
        "selectGoUpDirectoryOnEnter": true
    }
}
```
