### ISSUE TITLE
Use left and right arrows to go all the way up and down

### ISSUE THREAD

**Issue by inikolaev** [marta-file-manager/marta-issues#409]
My muscle memory pushes me to use `left` and `right` arrows to go all the way up or down, so I assume this was the behavior back in Far Manager days. Is it possible to implement something similar of maybe with custom configuration now?

**Comment by dieterguendisch** [comment]
yes, with keybindings like this:
```
"core.go.up": ["Left"],
"core.move.left": [],
"core.move.right": [],
"core.open": ["Right","Return"],
```

**Comment by dieterguendisch** [comment]
I use `Home` and `End` keys for this (when these keys are missing on your keyboard it's probably `fn+left` and `fn+right`)

**Comment by inikolaev** [comment]
Looks like it's not quite possible to make what I want. I want `left` and `right` to be able to move left and right in multi-column setup, but when there's no more column to move left or right is should behave like `PageUp` and `PageDown` correspondingly.

**Comment by inikolaev** [comment]
This is how it behaved in Far Manager and I just got used to it :)

**Comment by sirburpalot** [comment]
As far as I can tell, the behaviour described by inikolaev still hasn't been implemented.
