### ISSUE TITLE
[Question] Purpose of "core.lookup.mode"?

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#410]
I was wondering what is the purpose of the `"core.lookup.mode"` flag in settings? Cannot find any information about it and changing its value does not seem to change anything at my end. Thanks!

**Comment by yanex** [comment]
`core.lookup.mode` sets the default behavior for the Look up action.
By default it's 'prefix' – it works fast and in most of cases you get exactly what you looked for.
You have an option to set it to 'substring' – when the Look up will use substring search by default. It takes more time to show the results though you get more results.

Note that you can explicitly set a search mode for a query by prefixing it by `@:` (substring search) or `^:` (prefix search).
