### ISSUE TITLE
Set left arrow key (<) to go to the top of the list

### ISSUE THREAD

**Issue by jaroet** [marta-file-manager/marta-issues#425]
Hello,
I started using Marta just now (few days ago) and already loving it. Fast, small en keyboard focused. Just what I was looking for. 
I noticed one thing that I find hard to adjust to. Using the keyboard to navigate the files list I found that the up arrow key and the left arrow key both do the same thing, move the focus one file up. Seems to be redundant. 
Could it be made that the left arrow key goes to the top of the list (current directory). And if it is already on the top of that list then hitting the left arrow key again takes you to the parent directory. 
I know that backspace key does this already but I find that switching from the arrowkeys to the backspace  key is a little to big distance for me. Half the time I am hitting the powerkey of the enter key. And as I do already have my fingers on the arrowkeys hitting the left arrow key twice seems much more natural. 
It might be my way of doing things but I guess more people would prefer this way. 

If this is somehow already possible please let me know because I did not find it. 

Kind regards,
Jeroen

**Comment by yanex** [comment]
Hello, looks like this issue duplicates https://github.com/marta-file-manager/marta-issues/issues/409.

Except one thing: pressing `<` for one more time doesn't navigate to the parent directory. To be honest, I don't really like this feature as it's 'unstable' – it does really different things depending on the external condition (the current list element index). If you really need this behavior for some reason, you can write a plugin. The actual API docs are available here: https://marta.yanex.org/api/index.html.
