### ISSUE TITLE
Maybe add an optional 3rd pane for drives/mounts, favourites etc

### ISSUE THREAD

**Issue by DeeGeeGit** [marta-file-manager/marta-issues#449]
I think it'd be really useful to have an optional (like you have with the embedded terminal you can switch on/off) third pane to the left of the main two where you would have things like homedir, mounted/unmounted drives, and could drag folders in there to make favourites which when clicked on would update the last active pane with their location.

Things like alt+1 and alt+2 but available all the time.

**Comment by yanex** [comment]
Clone of #320.
