### ISSUE TITLE
Etty does not play nice with virtual Python environments subshells

### ISSUE THREAD

**Issue by jamesstidard** [marta-file-manager/marta-issues#453]
I use virtual environments for my Python projects in combination with [fish shell](https://fishshell.com) + [fish-pipenv](https://github.com/kennethreitz/fish-pipenv).

When I'm using Marta, and I move into a Python project's directory, the etty terminal stops appearing to respond, until I refocus the terminal. Then I see the `source path/to/venv` command. Then on exiting the directory the etty terminal is stuck in a limbo where it's either not responding or just not updating until focused. I have to end up force killing the terminal.

The gif below shows me unfocusing and refocusing the terminal to get to it behave. As well as it no longer following the directory of the Marta explorer after entering a virtual environment (the mzo-cli directory). 

![screen recording 2018-12-27 at 12 56 46 pm mov](https://user-images.githubusercontent.com/1797906/50481079-8b3a8e80-09d7-11e9-8cf2-5777c9a69896.gif)

Thanks.

**Comment by jamesstidard** [comment]
For anyone else with a similar setup/issue, I've got around this by setting a environ for etty that makes `fish-pipenv` think the subshell is already active.

```
# ~/Library/Application Support/org.yanex.marta/conf.json

{
    ...,
    "etty": {
        "environ": {
            "PIPENV_ACTIVE": "1",
        },
    ...,
}
```

**Comment by jamesstidard** [comment]
I actually just updated to 0.6 and this appears to be fixed 🎊

**Comment by yanex** [comment]
Great to hear! Anyway, thanks for reporting!
