### ISSUE TITLE
Add autoupdate

### ISSUE THREAD

**Issue by ruipacheco** [marta-file-manager/marta-issues#454]
Why not integrate [Sparkle](https://sparkle-project.org/) so we can get autoupdates, instead of manually downloading a new version?

**Comment by yanex** [comment]
@ruipacheco Marta uses Sparkle framework since the very first version. If it doesn't work for you, it's a critical bug.
Do the "Marta -> Check for updates" menu item start the update check?

**Comment by ruipacheco** [comment]
That button seems to work but when I start marta I get a modal window saying I should update. The usual behaviour is to notify that there is an update and then give the user to do so.

**Comment by yanex** [comment]
Now I probably understand what you're talking about.
Older versions of Marta had a limited lifetime and after its end, Marta forced you to install the newer version. That lifetime check was removed in 0.5.1 (the actual version of Marta is 0.6). In other words, the issue should be already fixed.
I'm very sorry for the inconvenience.

**Comment by ruipacheco** [comment]
Thanks!
