### ISSUE TITLE
Show all files from subfolders recursively

### ISSUE THREAD

**Issue by ww7** [marta-file-manager/marta-issues#469]
Suggest command, what show all files (folders) from current folder and subfolders
Windows Total Commander have this feature named Branch View (Ctrl+B)

**Comment by yanex** [comment]
Are you looking for the Flatten (Cmd+Shift+P, "Flatten") action?

**Comment by ww7** [comment]
Yeah, forget. Thanks!

**Comment by ww7** [comment]
What way to see size and number of selected files ?

**Comment by yanex** [comment]
Currently not possible, already fixed in the upcoming 0.6.1.
