### ISSUE TITLE
Search / Filter action not working anymore

### ISSUE THREAD

**Issue by fredclose** [marta-file-manager/marta-issues#471]
Using ⌘⇧P , I bring the action I see a list of possible actions 
starting from
Open
Open with ...
(...)
up to 
Change update check status

My understanding is that if I type something it should filter those actions 
but I type for example to type Clone 
the action 'Clone current directory to right' is not shown 

Am I missing something ?

**Comment by fredclose** [comment]
adding a picture to describe the problem
![screen shot 2019-01-22 at 09 09 09](https://user-images.githubusercontent.com/957192/51521105-d6ed2600-1e25-11e9-94fa-8462ecb975df.png)

**Comment by fredclose** [comment]
Strangely enough , I only have the problem with following themes 
Sakura 
Commander 
Classic

**Comment by yanex** [comment]
@fredclose Please check if the bug still reproduces in Marta 0.6.1 RC: #489.

**Comment by fredclose** [comment]
seems to be ok 👍
