### ISSUE TITLE
Error when moving in Trash (deleting) on FUSE mount and network shares

### ISSUE THREAD

**Issue by ww7** [marta-file-manager/marta-issues#472]
I use sshfs/ftp local mounts (FUSE mount) of remote servers and browse with Marta.
Found error (not able to delete) when moving in Trash on mounted remote's.
Finder do it.

**Comment by ww7** [comment]
Also not able to delete in network shares (mounted smb)

**Comment by krupenja** [comment]
This is probably the same as #147

**Comment by ww7** [comment]
> This is probably the same as #147

Yes. My inattention. Maybe just one button (Cancel or Abort) will be more clear

**Comment by yanex** [comment]
Closing as duplicate of #147.
