### ISSUE TITLE
Quick Select indication not very visible

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#478]
I think the Quick Select indicator in the lower-right corner of the pane is not very visible. This is especially apparent when you input text that results in no matches as there would be no colour highlighting anywhere.

![image](https://user-images.githubusercontent.com/26354715/51997535-980f3e00-24bf-11e9-80fc-027d0376dfdf.png)

I think you might consider making it more visible, e.g. by making the text the same colour used for highlighting files when there are matches.

**Comment by yanex** [comment]
I added an animated color highlighting on zero matches in 0.6.1.
Feedback is very welcome!
