### ISSUE TITLE
Cannot assign keybinding to Create symbolic link action

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#479]
1. Open conf.json
2. Add something like: `"core.create.symbolic.link": [ "Cmd+F1" ],` or `"core.create.symbolic.link": [ "Shift+F9" ],`
3. In Marta, enter the key combination assigned above.

Nothing happens. Both keybindings I tried (Cmd+F1, Shift+F9) can be successfully assigned to other actions.

**Comment by yanex** [comment]
The valid name is `core.create.symlink`. You can see the action identifiers right in the Actions panel (Cmd+Shift+P). Just hold the "Alt" key, and the ids will be shown.

**Comment by krupenja** [comment]
Yes, that works. Thanks for the tip!
