### ISSUE TITLE
First entry in Actions menu is in bolder and somewhat blurry font with Dark theme

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#483]
1. Use Dark theme in Marta.
2. Open Actions (Cmd+Shift+P).
3. Type some text.

The first entry (not the one under cursor) is in bolder and somewhat blurry font. This is especially evident on non-Retina displays, compare entries highlighted in red and green below:

![image](https://user-images.githubusercontent.com/26354715/52174983-22e48700-27a5-11e9-950e-fb774bdab150.png)

Sorry for nitpicking but this does make the first entry look a bit awkward, especially the hotkey assignment text.

No such problem with Classic theme.

**Comment by yanex** [comment]
@krupenja Please check if the bug still reproduces in Marta 0.6.1 RC: #489. I can't reproduce it there even without a 'retina' resolution.

![screenshot 2019-02-04 at 18 02 04](https://user-images.githubusercontent.com/95996/52216322-09c3ff00-28a7-11e9-96e9-8cb1612760f2.png)

**Comment by krupenja** [comment]
OK, I think I got it :) On my system this is only reproducible if "Use font smoothing when available" is on in System Preferences -> General. If that option is on, I get it even with 0.6.1 RC.

**Comment by yanex** [comment]
@krupenja Strangely, I can't reproduce the bug on 0.6.2. I tried to enable the font smoothing, and also set the non-retina resolution (Mojave 10.14.4 (18E226)).
Does the bug still reproduce on your environment?

**Comment by krupenja** [comment]
I am afraid I am still getting this on 0.6.2, macOs version same as yours. Same symptoms: only seems to affect dark themes, only with "Use font smoothing when available" enabled, more noticeable on my non-Retina monitor. Is there anything else I can do to help you investigate?

**Comment by krupenja** [comment]
Closing as cannot reproduce this on 0.7.
