### ISSUE TITLE
Available etty themes are not listed in default configuration

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#484]
1. Execute action Open default configuration.

There is a list of Marta themes in comments but there but no list of etty themes. Interestingly, [documentation](https://marta.yanex.org/docs#embedded-terminal) seems to imply that those should be listed there:

> You can configure the terminal theme, font and environment variables in conf.json. Refer to the default configuration file (Open default configuration action) to see all available options.

**Comment by yanex** [comment]
0.6.1 will contain the whole list of the bundled themes in the 'examples' section.
