### ISSUE TITLE
useMainThemeColors does not work

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#485]
1. Make sure that `useMainThemeColors` is set to true under `etty` in config.
2. Switch to Dark theme.
3. Open etty.

Result:

Etty is white.

![image](https://user-images.githubusercontent.com/26354715/52175156-48bf5b00-27a8-11e9-8268-f1aac0c75fac.png)

I think this is a regression but not 100% sure.

**Comment by krupenja** [comment]
Can no longer reproduce this in 0.6.1 RC. Was there a fix?

**Comment by yanex** [comment]
No. However, I suppose some other changes in the terminal configuration mapper could fix the bug.

**Comment by krupenja** [comment]
Ok, cool :)

**Comment by krupenja** [comment]
Have narrowed this problem down a bit: seems to only happen after a theme change if etty was open before the change. Updated issue description to reflect that.
