### ISSUE TITLE
Left & right configuration using Marco lang

### ISSUE THREAD

**Issue by dodalovic** [marta-file-manager/marta-issues#495]
yes, with keybindings like this:
```
"core.go.up": ["Left"],
"core.move.left": [],
"core.move.right": [],
"core.open": ["Right","Return"],
```

_Originally posted by @dguendisch in https://github.com/marta-file-manager/marta-issues/issues/409#issuecomment-408347480_

How do I achieve this using Marco config lang?

Thanks for wonderful product!

**Comment by yanex** [comment]
Just remap `Left` and `Right` hotkeys to other actions:

```
keyBindings {
    "Left" { id "core.go.up" }
    "Right" { id "core.open" }
}
```

Now you don't bind specific actions to hotkeys, you bind hotkeys to actions.
If you want to remove a key binding, just pass `null` as a value:

```
keyBindings {
    "Return" null
}
```

**Comment by dodalovic** [comment]
@yanex Brilliant! One more: how do I prevent that when I press right arrow key the file is opened? I'd just like doing nothing in the case of right key on file, whereas for dir, I'd like to enter it.

**Comment by yanex** [comment]
@dodalovic Marta has the "Open directory" action. It does exactly what you want.

**Comment by dodalovic** [comment]
@yanex Brilliant! Thanks!
