### ISSUE TITLE
Return does not open directories

### ISSUE THREAD

**Issue by noestreich** [marta-file-manager/marta-issues#498]
V0.6.1. - I did not change key-bindings in 
Return does not open directories. Even though it is matched to "core.open".
Instead it acts like  "core.open.with".
Looking in the menubar, in the "file"-menu, "open" is the only option missing an assigned key. 

<img width="258" alt="bildschirmfoto 2019-02-09 um 21 41 32" src="https://user-images.githubusercontent.com/309419/52526066-a75a6c80-2cb3-11e9-81f9-578aca82200d.png">

<img width="284" alt="bildschirmfoto 2019-02-09 um 21 43 36" src="https://user-images.githubusercontent.com/309419/52526079-c9ec8580-2cb3-11e9-81bf-ab9e11fdc5b9.png">

**Comment by noestreich** [comment]
after removing all key-bindings in the right pane of the config window, it works. 
it looks as if there are a couple of predefined customization-options not right. ()
And the order is not in the same order as the left panel. ("environment" for examle)
Why not start with a completely empty right panel, or one which looks exactly like the default?

**Comment by yanex** [comment]
In a fresh Marta installation, the configuration file looks like:
```
behavior {
    theme "Kon"
}
```

I think you had a previous version of Marta installed, and the configuration was incorrectly migrated during the update.

**Comment by noestreich** [comment]
That was definitly not the case. I had a huge configuration-file. 
Now i set it to the default and everything just works. Thanks for that,.
