### ISSUE TITLE
Add menu-entrys 'About', 'Issues'/'Homepage'

### ISSUE THREAD

**Issue by noestreich** [marta-file-manager/marta-issues#499]
It would be great to have an "about" menu-item. i just posted a bug-report and tried to check if i had the latest version installed. There is no obvious way to see the version-number right now. I resorted to command+i the selected 'marta.app' but a menu-item would be great. 

Should you plan to integrate an about-menu, put a link to the marta-homepage or issue-site in it as well - maybe just for the extended beta-period. 

Something like this: 
![about](https://user-images.githubusercontent.com/309419/52526262-4a13ea80-2cb6-11e9-99ec-b3c18259b296.gif)

**Comment by yanex** [comment]
"About Marta" menu item is available in the application menu (the screenshot is attached).
Do you have this item?
<img width="269" alt="screenshot 2019-02-15 at 04 31 27" src="https://user-images.githubusercontent.com/95996/52828653-b0e03c00-30da-11e9-8f6e-8d50e096146d.png">

However, it is a nice idea to add the "Homepage" item as well. Thanks!

**Comment by noestreich** [comment]
No i did not have the items. Thats why i _designed_  my mockup. But thanks for taking the time to show me what the menu should look like.  I did reset my configuration since, and now the menu is back. It looks like my configuration was [incorrectly migrated](https://github.com/marta-file-manager/marta-issues/issues/498) during the last update.

**Comment by yanex** [comment]
It's a very unfortunate that the migration mechanisms worked incorrectly for your configuration. I'm sorry for that. However, it's a one-time process, and the bug shouldn't affect new Marta users.
So, if you allow, I will close the bug report.
