### ISSUE TITLE
Use native keyboard shortcut handling

### ISSUE THREAD

**Issue by nanoant** [marta-file-manager/marta-issues#504]
Hi,
An ex-macOS developer here 🤓 and long time Forklift user. Also tried I supported Nimble Commander, fman. Used to be Total Commander plugin dev, still using it at work.

I have recently stumbled upon Marta and I am right now trying if it works for me. So far so good. Great work!

Now what bothers me at first sight is non-native macOS approach for keyboard shortcuts. In principle menu is not only alternative way to access app functions but it serves also as a glossary for keyboard shortcuts. Moreover I believe good macOS app keeps all its shortcuts properly exposed in the menu and it should rather not use different mechanism to do so as this no longer is explicit. Let's take sublime example where most of global shortcuts (not package specific) are exposed:
<img width="771" alt="zrzut ekranu 2019-02-16 o 11 34 55" src="https://user-images.githubusercontent.com/103067/52898621-313c9500-31e0-11e9-9eb7-f30a0c85db7d.png">

It seems Marta is somewhat half-way.
<img width="580" alt="zrzut ekranu 2019-02-16 o 11 35 50" src="https://user-images.githubusercontent.com/103067/52898612-1538f380-31e0-11e9-9d42-5fed117aa5b6.png">

Marta shows menu items shortcuts is some weird non-native way in parenthesis next to the item. In this way I can only presume that they are also not activated via menu actions, hence non-native approach.

Can you please reconsider that and expose all (aka everything) in the menu and use native menu keyboard shortcuts.

Thank you!

**Comment by yanex** [comment]
I'm really glad you liked Marta! Thanks!
I don't remember the exact reason why the default macOS menu hotkeys didn't work. All I know is that there were issues with custom hotkey handling so I had to switch to the current approach.
I will investigate this one more time. Thanks for the report!
