### ISSUE TITLE
More representative less abstract icon

### ISSUE THREAD

**Issue by nanoant** [marta-file-manager/marta-issues#505]
Hi Yan,
I would like to humbly propose an more representative, and less abstract icon for Marta, that in my humble opinion does play well with Apple icons.

![marta-icon-compare](https://user-images.githubusercontent.com/103067/52900640-8d131800-31f8-11e9-8bd8-135b6cbd56af.png)

Here are two version, tilted and straight:
![marta-icon-256x256-tilted](https://user-images.githubusercontent.com/103067/52900668-c9467880-31f8-11e9-9641-3145019c5719.png)
![marta-icon-256x256-straight](https://user-images.githubusercontent.com/103067/52900670-cc416900-31f8-11e9-974a-3c5dc528159e.png)

While I do algorithms for a living, I sometimes do icons for a pleasure 😃 (e.g. Photoline)
Let me know what do you think. If you like it, I can provide 1024x1024 version and donate the icon to the project.

**Comment by warpkanal** [comment]
Always felt the same about the current icon. I really like your proposed one!

**Comment by yanex** [comment]
Hello @nanoant!

I must say I like your icon, especially the tilted one. It's carefully done. Thank you!

However, I don't think that application icons *must* reflect its purpose. From time to time I try alternative file managers as a source of inspiration. A majority of them have a disk, a list or a table on the icon. As a result, I can hardly remember which one do each application have. On the contrary, Forklift has, ba-doom, a forklift on its icon – and I think it's brilliant. It definitely stands out – and, once seen, you never forget it.

Lots of popular applications have abstract icons. Here are just a few examples: VLC Media Player, Transmission, TextMate, Atom. Even the Finder icon is said to be [influenced](https://www.quora.com/What-is-the-design-story-behind-the-OS-X-two-face-one-face-Finder-icon) by a Picasso drawing. Marta has a clean, minimalistic one – and, in my opinion, it matches Marta goals pretty well – "a lightweight but people-friendly file manager".

However, I realized the Marta icon is a bit too flat, compared with others in the dock. I will experiment with it, and probably modify the background a bit.

**Comment by nanoant** [comment]
> However, I realized the Marta icon is a bit too flat, compared with others in the dock. I will experiment with it, and probably modify the background a bit.

My biggest concern was that the icon was somewhat standing out from the crowd on my Dock. I would prefer something that blends with the rest. Like you mentioned, it does not need to reflect its purpose. Apple anyways deviated from that direction few years ago.

But it would be nice it is something that you can easily describe too, e.g. *"click there on blue happy face (Finder), a stamp with an eagle (Mail)". How would you describe Marta? To me closest description that comes to my mind is a "lifebuoy" 😉. Maybe then lifebuoy could be nice metaphor here, and we can make it look like lifebuoy?

![image](https://user-images.githubusercontent.com/103067/53566417-6213b700-3b5c-11e9-91ff-3236b3b68c8e.png) (random Google images picture, I hold no copyrights for that or whatsoever)
