### ISSUE TITLE
Are Marta copy / move operations equivalent to Finder?

### ISSUE THREAD

**Issue by nanoant** [marta-file-manager/marta-issues#507]
This isn't an issue exactly but just a question. Is Marta providing binary exact file / directory copy operations to Finder. E.g. are all file (extended) attributes preserved.

Just out of curiosity is Marta using `NSFileManager` or some more low level such as [Carbon Core File Manager](https://developer.apple.com/documentation/coreservices/carbon_core/file_manager?language=objc). What I can see Apple has depreciated it, but `NSFileManager` isn't exactly the equivalent, since it does not e.g. provide progress to the file operations.

**Comment by yanex** [comment]
Marta uses the `copyfile()` function for copying individual files for the local file system. These flags are passed: `COPYFILE_STAT | COPYFILE_ACL | COPYFILE_XATTR | COPYFILE_DATA`.

Extended attributes are not copied for the directory items. #509
Also, currently there is no way to control attribute copying. #510

**Comment by nanoant** [comment]
@yanex Thanks for the explanation. Using `copyfile()` makes a lot of sense, but I presume all directory tree handling has to be done in the app then?

From the functionality standpoint [`FSCopyFileAsync`](https://developer.apple.com/documentation/coreservices/1566285-fscopyobjectasync?language=objc) looks like most feature complete one as if I am not wrong also handles directory tree, like in this complete Apple's example:
https://developer.apple.com/library/archive/samplecode/FSFileOperation/Listings/main_c.html

Unfortunately Apple has deprecated it in 10.8 without providing real equivalent (`NSFileManager` is not). Here is nice attempt to clarify that: https://forums.developer.apple.com/message/38912#38912
Of course classical Apple no response whatsoever.

I presume it is still present in 10.14 despite deprecation though. Maybe you could try if this works for whole trees?

**Comment by yanex** [comment]
Carbon file manager doesn't support APFS, making it a no-go for Marta.
I'm not sure if the all-in-one solution will be sufficient, as it has to handle file/directory clashes and errors. Also, Marta supports arbitrary file systems (including archives, network FSs, purely virtual file systems), so the tree handling functionality is still needed.

**Comment by nanoant** [comment]
Fair enough.

Side-comment: I can only regret that the file operations interface is shrinking rather than expanding to allow mounting 3rd party FS right from user-space in macOS.
