### ISSUE TITLE
[Feature Request] Hijack Finder opening and instead open Marta

### ISSUE THREAD

**Issue by gochev** [marta-file-manager/marta-issues#515]
TotalFinder an another alternative of the Apple finder have the crazy way to hijack the starting of a finder and instead to start Total Finder.

I hate the fact that I by mistake am still opening finder. Also in order to REMOVE the finder from the bar you need to stop SIP.

It will be crazy great if Marta can hijack the Finder starting and instead of the crappy Finder to start Marta instead.

**Comment by yanex** [comment]
I don't think that patching Finder is a good idea. Apple continously makes harder to do nasty things with the system binaries. As far as I know, the changes in application isolation in 10.13 made TotalFinder more or less unusable – one have to open the system protection to continue using TotalFinder.
It is unlikely that Marta will have such functionality out-of-box someday. However, I think it can be implemented as a stand-alone utility (both by me or some other developer).

**Comment by sublimal** [comment]
I did some digging into this and wanted to share my findings for anyone else wanting this behaviour.

On latest macOS (eg: 12.x) it isn't possible to change the default file handler away from Finder (even with SIP disabled) without some nasty hackery (as pointed out by yanex). eg (using [swda](https://github.com/Lord-Kamina/SwiftDefaultApps) results in default error from LaunchServices):

```
% swda getHandler --URL file
/System/Library/CoreServices/Finder.app
% swda setHandler --URL file --app /Applications/Marta.app
SwiftDefaultApps ERROR -10810: An unknown error has occurred.
```

It is however possible to register Marta as the handler for generic items:

```
% swda setHandler --UTI public.item --app /Applications/Marta.app
SwiftDefaultApps SUCCESS: Default handler has succesfully changed to org.yanex.marta
% swda setHandler --UTI public.folder --app /Applications/Marta.app
SwiftDefaultApps SUCCESS: Default handler has succesfully changed to org.yanex.marta
```

If you're able to identify the [Uniform Type Identifier](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html) which are  opening in Finder you can change the default handler to Marta. For me this was mostly problematic with folders (`public.folder`). Currently (0.8.1) Marta has UTI Viewer support for basic base class  in the physical hierarchy (`public.item`) - if the UTI isn't conformant to that, it probably shouldn't be handled by a generic file manager.

If you're really committed you could try something like running output of:

```
% swda getUTIs|grep '/Finder.app$' | cut -f1 | xargs -n1 -I{} echo swda setHandler --UTI {} --app /Applications/Marta.app
```

Relates #861 #870 #518 (possibly more). Hopefully they'll see the ping - saving updating each issue individually
