### ISSUE TITLE
Preserve view folder settings (ordering, columns, display mode),  Presets 

### ISSUE THREAD

**Issue by ww7** [marta-file-manager/marta-issues#516]
Cool Finder feature to save custom view for some folders. 
For e.g. Downloads folder have always Modified ordering.

Is a possible to make presets of View and change it with commands?

Also currently not possible to change ordering just with keyboard from the box. 
With witch command i would make custom shortcut for descending modified?

**Comment by yanex** [comment]
You can change ordering with a keyboard.

1. Open the "Ordering…" action (`Cmd+Shift+P`, "Ordering…").
2. Choose the new ordering (`N` for name, `S` for size and so on). Option (Alt) key allows you to set the bottom checkboxes, e.g. `Opt+A` for Ascending.  
4. Press `Return` to apply the new ordering.

**Comment by ww7** [comment]
Cool.

My request about remembering of sorting for different folders. 
I know it is a complicated, probably is a possible to use .DS_Store ?

Alternatively, if possible to set keybindings for predefined ordering?
For example, in download folder I need sorted by Modified and currently I need twice click or more keyboard commands just to find last downloaded files and next turn by Name back, so complicated

Например у меня в основном отсортировано по имени, но иногда в папке с загрузками нужно просмотреть последние файлы, приходится или два раза кликать по колонке и потом снова для сортировки по Имени. На клавиатуре это еще более затратно для рутинного действия.

Моя запрос в возможности задать режим сортировки для конкретных папок (например в конфиге), или возможность создать кейбинд на нужную сортировку (напр. дата по убыванию).

**Comment by eugenesvk** [comment]
> I know it is a complicated, probably is a possible to use .DS_Store ?

Can we please use configs instead of these `.DS_Store` file turds? Would also be easier to paste your preferred layout/sorting to some other folders
