### ISSUE TITLE
Question: exiting DirStat mode?

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#528]
What is the proper way to exit DirStat mode? Say, I launch it inside `~/Library`. Then, I want to navigate up to `~` but neither pressing Backspace or Enter on .. does anything. Am I missing something?

**Comment by yanex** [comment]
DirStat actions opens a separate tab. Just close the tab, and that’s it :)

**Comment by krupenja** [comment]
Got it thanks!
