### ISSUE TITLE
Add isPackage or similar method to VirtualFile

### ISSUE THREAD

**Issue by gawashburn** [marta-file-manager/marta-issues#53]
It is possible to detect whether a directory is an application bundle with the `isApplication` method, but it would also be handy to be able to check if the directory (say a `.plugin`) is a package.

**Comment by yanex** [comment]
`isPackage` is available in `LocalFile`: https://marta.yanex.org/api/Protocols/LocalFile.html.

**Comment by yanex** [comment]
But you're right: `VirtualFile.isApplication` does not make sense. In the future versions, it will be moved to `LocalFile`.

**Comment by gawashburn** [comment]
Thanks!  I'll cast to `LocalFile` if appropriate for both.
