### ISSUE TITLE
Cmd-i not working on external drive

### ISSUE THREAD

**Issue by yusernamelol** [marta-file-manager/marta-issues#530]
Nothing happens when I hit Cmd-i on external drives, files or folders, doesn't matter. Finder works as expected.

**Comment by yanex** [comment]
Unfortunately, I couldn't reproduce the issue on my side. Can you please try if everything works in Marta 0.6.2?
Also, the "Get info" window appears deactivated. I didn't find a way to activate it without activating the Finder app. The custom dialog implementation (#292) should fix this.

**Comment by yusernamelol** [comment]
It looks like 0.6.2 fixed it.
