### ISSUE TITLE
Possible to attach remote/cloud drives (dropbox, onedrive,etc)

### ISSUE THREAD

**Issue by ckluis** [marta-file-manager/marta-issues#534]
It could be just me, but I can't figure out how to attach cloud storage to the folder structure.

**Comment by yanex** [comment]
You can use third-party tools such as [CloudMounter](https://cloudmounter.net/) or FUSE to mount remote storage.
I created to separate issues #543 and #544 to track progress for each file system.
Please create separate issues if you want Marta to support a different VFS.
