### ISSUE TITLE
macOS 10.12 support?

### ISSUE THREAD

**Issue by twardoch** [marta-file-manager/marta-issues#535]
Marta 0.6 works in macOS 10.12 but 0.6.1 requires 10.13. I don’t see this mentioned in https://marta.yanex.org/changelog — was this a deliberate choice? 

macOS 10.12 is still reasonably popular among some developers who develop apps that support older OSes. If there are no technical reasons why 10.12 was dropped, please bring it back, otherwise, please mention it in the changelog :)

**Comment by krupenja** [comment]
Should be fixed in the next release https://github.com/marta-file-manager/marta-issues/issues/517
