### ISSUE TITLE
Eats "a lot" of CPU when idle

### ISSUE THREAD

**Issue by bligny** [marta-file-manager/marta-issues#550]
On my MacBookPro (model 2017, 2.8 GHz Intel Core i7), Marta v0.6.2 is eating 6% of CPU...**when completely idle.**

In such, this is +/- reasonable but yet a huge difference compared to other resource-consuming running application, such as Chrome, Skype, etc.. which are taking 0.2 up to 0.4%
=> see attached screenshot.

![image](https://user-images.githubusercontent.com/19853549/58404822-51dd7c00-8066-11e9-8ada-e6f897df71da.png)

**Comment by krupenja** [comment]
Can confirm, on my MBP 13'' (mid 2014, 2,6 GHz Intel Core i5) I also get around 6-7% CPU usage when  Marta is focused but doing nothing.

**Comment by yanex** [comment]
This is definitely a critical issue. I will fix this in the next release.
