### ISSUE TITLE
Enter/Return key bindings

### ISSUE THREAD

**Issue by kambala-decapitator** [marta-file-manager/marta-issues#559]
Wanted to bind Rename to Enter (Fn+Return) like in Path Finder, but turned out Enter is the same as Return, and Fn doesn't have any effect. Is there a workaround?

**Comment by yanex** [comment]
Use the `KeypadEnter` key name as Fn+Return actually corresponds to the Enter key from the NumLock section:

```
keyBindings {
    "KeypadEnter" { id "core.preview" }
}
```
