### ISSUE TITLE
macOS 10.15 Catalina beta and "${system.applications}" in Favorites

### ISSUE THREAD

**Issue by haakonstorm** [marta-file-manager/marta-issues#561]
- Latest Catalina beta and
- latest Marta

Applications "${system.applications}"

in `favorites.marco` resolves to `~/Applications` instead of `/Applications`
(which now in Catalina in turn is a combination of contents in /Applications and `/System/Applications`

**Comment by VKondakoff** [comment]
The same happens in Catalina release.

**Comment by yanex** [comment]
There will be a new variable (`all.applications`) that will point to `/Applications`.
