### ISSUE TITLE
Action to select current item

### ISSUE THREAD

**Issue by haakonstorm** [marta-file-manager/marta-issues#563]
# I'm trying to map `space` to toggle the *currently selected item*.
- The action `core.select` alone doesn't work.
- I'd love to see a `core.invert.selecteditem` or similar.

## Use case scenario
- Map ´shift+cmd+c` to `core.copy` and `shift+cmd+m` to `core.move`
- Select files individually with `space`
- Copy or move files with keyboard

Thanks for a great app!

**Comment by krupenja** [comment]
Have you tried `core.select.move.down`. It also moves the highlight down but perhaps this is acceptable to you.

**Comment by haakonstorm** [comment]
Brilliant! I'm sure if yanex added the feature I requested, I'd immediately realize what I *really* was after was select and move down, just like in the old days with Norton Utilities and the like!

**Comment by haakonstorm** [comment]
@krupenja 's suggestion is an even better solution and is *already implemented* in the awesome Marta!

**Comment by yanex** [comment]
Just in case if you (or someone else) need the `core.select` action without moving the cursor, it will be available in 0.7.
Effectively, it will invert the current selection. However, I named it to match other similar actions, such as `core.select.move.down` (they also invert it).

**Comment by emilkaae** [comment]
I am having trouble making a key binding to `core.select` in version 0.8.1. I'd like to have e.g. "Insert" mapped to this action, for example. All my attempts so far have been ineffable and unsuccessful. Should this work?

**Comment by haakonstorm** [comment]
Just had a quick glance on my own setup, I have this line:
```
    "Shift+Space" { id "core.select.move.down" }
```
Perhaps this will help you further along?
Try to map FROM another key, to something that you know work, so that you can change one thing at a time. 
I havent tried `core.select` (aka "invert") myself but as mentioned above it should be implemented by now. 

Thanks to yanex for all his awesome work.

**Comment by emilkaae** [comment]
~~Thanks! I have tried all sorts of things—now also this, and I get no results at all. Any ideas what could be wrong?~~

Ok, a restart of Martha seemed to do the trick for me. I am using Karabiner Elements to remap a windows keyboard at work, so maybe that interferes... 

(oh, and yes, big thanks to Yanex for Marta! I am completely overwhelmed about how well this software is written; a real gem!)

**Comment by haakonstorm** [comment]
Perhaps [Key Codes](https://apps.apple.com/us/app/key-codes/id414568915?mt=12) can help you figure out more, also what Karabiner ultimately sends after the remap. Perhaps you can change your remap.
