### ISSUE TITLE
Add dialogs for changing the UNIX permissions of a file (chown/chmod)

### ISSUE THREAD

**Issue by sirburpalot** [marta-file-manager/marta-issues#583]
For your reference, this is how the feature is implemented in Midnight Commander.

<img width="1114" alt="Screen Shot 2019-10-03 at 17 48 07" src="https://user-images.githubusercontent.com/1429516/66137625-09326280-e606-11e9-911e-7e125c6f2301.png">

<img width="1114" alt="Screen Shot 2019-10-03 at 17 48 10" src="https://user-images.githubusercontent.com/1429516/66137642-0e8fad00-e606-11e9-90a3-8cb7bb9c755a.png">

**Comment by yanex** [comment]
Hello @sirburpalot! I will link the issue to the existing one (#257).
