### ISSUE TITLE
Unable to move files on FAT32 formatted USB pendrive

### ISSUE THREAD

**Issue by gamerboy** [marta-file-manager/marta-issues#584]
Hi,
I'm unable to move file from Mac to a FAT32 formatted usb pendrive.
All I get is 

```
Can not move "filename".
Cross-device link.
```

* Marta Version:  0.7
* macOS Mojave 10.14.6 on MacBook Air 2018 Retina

**Comment by yanex** [comment]
Hello @gamerboy! Thanks for the report! Other users reported this (#571), so I will close the bug as a duplicate. This is definitely a critical bug to be fixed in the upcoming Marta version
