### ISSUE TITLE
Unable to create folder in /usr/local/ (permission denied)

### ISSUE THREAD

**Issue by VKondakoff** [marta-file-manager/marta-issues#587]
Hello!

I was unable to to create folder in /usr/local/ -  there is an error: permission denied. The same folder was successfully created from Finder (after filling password).

<img width="768" alt="image" src="https://user-images.githubusercontent.com/230824/66679669-6a49de00-ec77-11e9-8de5-ac5a685411e2.png">

Marta 0.7, Catalina

**Comment by yanex** [comment]
Clone of #177.
