### ISSUE TITLE
Usability: not clear enough which pane is currently active (at least in Kon theme)

### ISSUE THREAD

**Issue by VKondakoff** [marta-file-manager/marta-issues#591]
I just found myself periodically pressing Tab just to find out - which pane is currently active: there is no good visual confirmation of this (if the selected files are scrolled out).
Her is an example, try to guess the active pane (it is impossible!):

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/230824/66688147-14ccfb80-ec8e-11e9-9464-a214f436c626.png">

I'm pretty sure, the active pane should have some visual sign of being active. Maybe something like this? (sorry for a quick mockup):

![image](https://user-images.githubusercontent.com/230824/66688207-45ad3080-ec8e-11e9-837e-fb1f4acd97af.png)

There may be a good idea to visually highlight the font in the breadcrumb area of active pane as well...

**Comment by yanex** [comment]
Normally, you have a cursor in the active panel. Isn't it enough for you?
<img width="1422" alt="Screen Shot 2020-07-07 at 11 43 27" src="https://user-images.githubusercontent.com/95996/86695035-2689d680-c047-11ea-9e0c-82d233755321.png">

**Comment by yanex** [comment]
I will close the issue as it seems to be resolved. Please leave a comment if it isn't.
