### ISSUE TITLE
There is no dedicated key to select files/folders (and no Select action in Actions panel)

### ISSUE THREAD

**Issue by VKondakoff** [marta-file-manager/marta-issues#592]
As far as I can see, currently there is no dedicated key to select files/folders (and no Select action in Actions panel). It is suggested to use Shift+Arrows to do this, but it is not as intuitive as having a dedicated key, which can be used in conjunction with arrows. 
As far as I remember, in console file managers the Ins key was used for this purpose.
What do you think about this? Maybe I'm just overlooking something obvious here?

BTW, there is a typo in the docs in the Selection section: "You can select items using the ⇧ and ⌃ keys."

**Comment by VKondakoff** [comment]
Hmm... Looks like on the Mac keyboard there is no unused single key to assign to Select file/folders action. Any ideas? The Eject key?

**Comment by VKondakoff** [comment]
It turns out there IS a Select action: [core.select](https://github.com/marta-file-manager/marta-issues/issues/563) . But for some reason it is not visible in Actions list. Bug?

**Comment by yanex** [comment]
Base actions are not shown in the Actions panel as having "Select and go left", "Go down" and many other actions make the panel cluttered.
However, I agree, it makes sense to have the `core.select` action there.
