### ISSUE TITLE
FR: 'New folder with selection' action or plugin

### ISSUE THREAD

**Issue by VKondakoff** [marta-file-manager/marta-issues#597]
One of the useful Finder features was 'New folder with selection':

<img width="351" alt="image" src="https://user-images.githubusercontent.com/230824/66703240-1ee80c00-ed19-11e9-9006-d1c8910735af.png">

Please, implement something like this in Marta as an action (or, maybe, plugin).

**Comment by yanex** [comment]
Clone of #127.
