### ISSUE TITLE
Play sound at the end of (lengthy) operations

### ISSUE THREAD

**Issue by VKondakoff** [marta-file-manager/marta-issues#603]
While testing Marta I have noticed, that I missed the end of several lengthy operations (copy/move files, calculating directory size), because I get used to the Finder way of playing sound at the end of every file operation. 
Maybe it is a good idea to add such a (configurable) option to Marta as well?
Thank you!

**Comment by yanex** [comment]
Sounds nice, and pretty easy to implement.
I will add this in the next version of Marta.
