### ISSUE TITLE
Auto selected after renaming with same name

### ISSUE THREAD

**Issue by gyli** [marta-file-manager/marta-issues#608]
There is an odd behavior, that after renaming a file, if a different name is given, Marta would not select the file. While if I keep the same file name and still click "Rename", Marta will select this file. I assume it is a bug instead of an intentional feature.

**Comment by yanex** [comment]
In theory, the file should be selected. However, in practice, it's not selected sometimes (also see #487). Can you reproduce the bug, or it only appears sporadically?

**Comment by gyli** [comment]
Yes, it happens all the time for me. This is the recorded screen. https://share.getcloudapp.com/mXu7gerk

Here I was trying to rename it, but not changing the name first, the file would be selected; Then I try to rename it with name changed, while the file is not selected this time. I think the behavior should be unified. However, I also think it it makes more sense not to select the file after renaming.
