### ISSUE TITLE
Copy Paste by hotkeys don't work in rename file dialog

### ISSUE THREAD

**Issue by skojin** [marta-file-manager/marta-issues#614]
It was closed, but issue https://github.com/marta-file-manager/marta-issues/issues/551 is still here 

CMD+A not works too

**Comment by yanex** [comment]
I will re-check. Thanks!

**Comment by 1mS3r** [comment]
I'm using Marta 0.71 and can't reproduce this bug
[Screen Recording 2020-09-03 at 00.02.27.mov.gz](https://github.com/marta-file-manager/marta-issues/files/5165027/Screen.Recording.2020-09-03.at.00.02.27.mov.gz)

**Comment by skojin** [comment]
here my recording, and it show bug for me
I have bug on guest user of my mac (macos 10.12.6), but it works well for other mac with macos 10.13.6

[Screen Recording Marta.zip](https://github.com/marta-file-manager/marta-issues/files/5166549/Screen.Recording.Marta.zip)
