### ISSUE TITLE
"open external terminal here" and "go forward" shortcuts aren't updated in menubar

### ISSUE THREAD

**Issue by kambala-decapitator** [marta-file-manager/marta-issues#617]
I've changed shortcut in settings:
```lua
keyBindings {
    "Cmd+[" { id "core.back" }
    "Cmd+]" { id "core.forward" }
    "KeypadEnter" { id "core.rename" }
    "Cmd+Control+T" { id "core.open.terminal.here" }
}
```

but in menubar it still shows default value:
![Screenshot 2019-12-04 at 21 06 43](https://user-images.githubusercontent.com/1557784/70168589-3b317500-16da-11ea-8152-6b4dea65982c.png)

To clarify: it's just a display bug, my changed shortcut works.

The same issue is with Go - Forward.

Go - Back and Rename show correct overridden shortcuts though.

EDIT: after some relaunches it seems that correct shortcuts are completely random: some are correct, some are not.

**Comment by yanex** [comment]
Even if you set new hotkeys, ones in the default configuration still work. In Marta 0.7.1 a random key equivalent is displayed in the menu. In 0.7.2 this will be fixed, and the same one will be preferred.
