### ISSUE TITLE
[swift docs] list of bundle types is wrong

### ISSUE THREAD

**Issue by kambala-decapitator** [marta-file-manager/marta-issues#619]
from https://marta.yanex.org/swift-api/index.html

> A plugin is a macOS bundle (.plugin and .bundle extensions are supported).

The latest version doesn't even try to load `.bundle` plugins based on the console log, only `.plugin` works.

**Comment by yanex** [comment]
Hello @kambala-decapitator!
You are right, the documentation has a bug.
However, I would recommend you to use the Lua API instead. Swift API is deprecated and will be removed in the next Marta release.

**Comment by kambala-decapitator** [comment]
Thanks. I've been trying to use Lua API with no success, please see #616

**Comment by yanex** [comment]
The Swift API will be removed in the next version of Marta, so I will close the issue as obsolete.
