### ISSUE TITLE
will you make it for linux

### ISSUE THREAD

**Issue by dackdel** [marta-file-manager/marta-issues#620]
Or flavours of linux?

**Comment by yanex** [comment]
Hello @dackdel!
Marta was intended as a Mac application.
If someone ports Foundation/Cocoa libraries to Linux, it will be possible to make a Linux port.

**Comment by Ma3yTa** [comment]
@yanex  please check http://www.gnustep.org/

**Comment by ghost** [comment]
@yanex please do so as soon as possible, I really like the way it looks and would like to have it on my Linux machine.
As @ma3yta has pointed out, GNUStep already has an open source implementation of Cocoa/Foundation libraries.

**Comment by yanex** [comment]
Hello @nemecekjh!
Unfortunately, now it's hardly possible as Swift/GNUstep interop is not here yet.
https://forums.swift.org/t/state-of-gnustep-interop/50950
