### ISSUE TITLE
Preview glitch

### ISSUE THREAD

**Issue by otto-md** [marta-file-manager/marta-issues#625]
Hi, thanks for a really nice app.

Ive noticed two small issues:

1. If I preview a file by pressing space (tried with pdf, mp3 and mp4) it seems like the file starts to play for a couple milliseconds and then restart. Its so little so its almost not noticeable.
2. In the menus the keyboard shortcuts are printed like this `Preferences (⌘,)` but the macOS standard is that the keyboard shortcut is right aligned, see screenshot below.
<img width="326" alt="Screenshot 2020-01-10 at 18 04 12" src="https://user-images.githubusercontent.com/31409359/72171927-35fbd000-33d4-11ea-9a0c-133589e5b8b2.png">

**Comment by yanex** [comment]
The second problem is a clone of #504.
I will treat this issue as (1) only.
