### ISSUE TITLE
Glitches in terminal window

### ISSUE THREAD

**Issue by dreadolph** [marta-file-manager/marta-issues#628]
Version 0.7.1
macOS Catalina 10.15.2 (19C57)

2 panels, same folder, Cmd-O -> open terminal (macOS terminal, bash)

Now if you resize bottom terminal window, text in window glitches inside,

![MartaGlitch](https://user-images.githubusercontent.com/7466767/72379782-8739f580-372d-11ea-9b73-92f26ec37efb.gif)

**Comment by dertuxmalwieder** [comment]
Potentially related:

Open the terminal, then keep Cmd-Alt-O pressed. You will see that, over time, the layout of the terminal window changes, as if the lines would become shorter.
