### ISSUE TITLE
Where are the default themes located?

### ISSUE THREAD

**Issue by hrvstr** [marta-file-manager/marta-issues#635]
I want to create a custom theme but can't find the location of the default themes. Is there any documentation how to create themes?

**Comment by yanex** [comment]
Hello @hrvstr! You can put custom themes to `~/Library/Application Support/org.yanex.marta/Themes`.

See https://marta.yanex.org/docs/#themes for more information.

**Comment by hrvstr** [comment]
Sorry for wording this badly. I know where to place custom themes but I need an example theme file (e.g. one of the defaults themes) so I can see what values need to be set!

**Comment by yanex** [comment]
Ah, sure. You can find the built-in themes here: `/Applications/Marta.app/Contents/Resources/themes`.
