### ISSUE TITLE
Multiple actions in keybindings - possible?

### ISSUE THREAD

**Issue by haakonstorm** [marta-file-manager/marta-issues#638]
```
keyBindings {
  "Tab" {   
    id "core.change.current.pane" 
    id "core.swap.panes" 
  }
}
```
I'm trying to get Marta to just interchange the path with the path in the inactive pane. :)

**Comment by yanex** [comment]
I will add a virtual action that accepts other action ids in arguments.

**Comment by yanex** [comment]
Here's the syntax (Marta 0.8):

```
keyBindings {
    "Cmd+Shift+A" {
        id "core.run.actions"
        actions {
            <action id 1> <args>
            ...
            <action id N> <args>
        }
    }
}
```

e.g. 

```
keyBindings {
    "Cmd+Shift+A" {
        id "core.run.actions"
        actions {
            "core.open" null
            "core.go" null
        }
    }
}
```

**Comment by haakonstorm** [comment]
Awesome!
Possible to become beta - tester somehow?

**Comment by yanex** [comment]
Just download the binary from here :)

https://github.com/marta-file-manager/marta-issues/issues/688

**Comment by sublimal** [comment]
Can this syntax be added to the documentation?
Alternatively an example in the preferences/config would be helpful.
