### ISSUE TITLE
Cannot navigate confirmation dialog using keyboard

### ISSUE THREAD

**Issue by auduchinok** [marta-file-manager/marta-issues#641]
It's be great if it was possible to focus different buttons using Tab in this window:
<img width="564" alt="Screenshot 2020-05-02 at 17 50 14" src="https://user-images.githubusercontent.com/3923587/80867575-83f75500-8c9d-11ea-9d06-9599c5c682f3.png">

I do have the corresponding macOS setting enabled:
<img width="780" alt="Screenshot 2020-05-02 at 17 50 31" src="https://user-images.githubusercontent.com/3923587/80867589-9a9dac00-8c9d-11ea-92af-01fdf4bf6d30.png">

It'd also be great if `Apply to all` was focused so it'd be possible to enable it using Space and then hit `Replace` using Return.

**Comment by h0tk3y** [comment]
Possible duplicate of https://github.com/marta-file-manager/marta-issues/issues/637
See the comments under that issue for some keyboard mnemonics for the buttons. There's not way to toggle 'Apply to all' with keyboard, though.

**Comment by auduchinok** [comment]
@h0tk3y Yes, I think it's indeed a duplicate. I left a comment in #477 saying that it's possible to use Tab to change focus.
