### ISSUE TITLE
Mac Menu search doesn't work

### ISSUE THREAD

**Issue by auduchinok** [marta-file-manager/marta-issues#643]
There's no Help -> Search for searching for actions.
`Cmd+?` opens Apple logo menu.

**Comment by h0tk3y** [comment]
If that might help, there's a separate keyboard shortcut for actions search, Cmd+Shift+P.

**Comment by auduchinok** [comment]
@h0tk3y Thank you, I'm aware of this dialog. The Menu search is an easy way to see if some action is available via macOS Menu, and to find it there which in some situations may help in discovering related actions nearby.
