### ISSUE TITLE
What is the ID of Look up here command?

### ISSUE THREAD

**Issue by nausher** [marta-file-manager/marta-issues#644]
I wanted to map the Key Binding for the "Look up here" command, but I cannot find its ID in the preferences or in the documentation - https://marta.yanex.org/blog/look-up/

**Comment by haakonstorm** [comment]
```bash
find /Applications/Marta.app/Contents/Resources/ -type f -exec strings {} \; | grep -i 'lookup'
```

<img width="900" alt="Screenshot of iTerm2 (18-06-2020, 13-44-02)" src="https://user-images.githubusercontent.com/193781/85016309-c7cced80-b169-11ea-9bd2-c01044e91a10.png">

**Comment by yanex** [comment]
@nausher If you press the Alt/Opt key in the Actions panel, identifiers for all displayed actions will be shown.

**Comment by nausher** [comment]
Thanks for the Alt/Opt key tip @yanex that is really helpful.
Thanks @haakonstorm for the tip.
