### ISSUE TITLE
Invent some consistent way of presenting all available shortcuts in a window

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#660]
Marta supports keyboard access in all dialog windows. However, the hotkeys are hard to discover.
There should be a way to present the available hotkeys to the user. macOS doesn't provide a standard way to do it (unlike Windows, for instance, that underlines 'hot' letters on pressing Alt), so Marta should probably invent its own.

**Comment by grossjohann** [comment]
It just occurred to me:  I think Sublime Text is doing this.  You can show a tooltip showing the keyboard shortcut when the user hovers over a UI element.

It's interesting that both IntelliJ and Sublime Text are cross-platform apps, so they take inspiration from other platforms.

I've looked at the Mac-only TextMate and CotEditor, and they do not appear to offer any hints for keyboard shortcuts in .  (I looked in the find dialog.)

**Comment by yanex** [comment]
I've implemented an overlay that appears on holding Opt (Alt) key.

![opt-ordering](https://user-images.githubusercontent.com/95996/91618128-8ad07300-e9c4-11ea-9bcd-f8e21bb8d167.gif)
