### ISSUE TITLE
Play sound when deleting files

### ISSUE THREAD

**Issue by 12-Seconds** [marta-file-manager/marta-issues#672]
I've grown used to the sound Finder plays when deleting files. Would It be possible to do this with Marta as well?

**Comment by yanex** [comment]
Hello, @12-Seconds!

Thanks for the suggestion! I've already added an "async operation completion sound" preference in 0.8 (#603). However, now I understand the sound should probably be different for different operations.
I will definitely change the feature allowing more personalization.
