### ISSUE TITLE
API for getting the current file

### ISSUE THREAD

**Issue by nadav96** [marta-file-manager/marta-issues#677]
Hi, how can one access the current file/folder (the one which the command was fire from) from the ActiveContext object?
Followup is how to determine if it's a file or a directory?

Is it possible to have some example plugins written in Lua ( Modifying files, drawing UI etc..)?

Thanks!

**Comment by yanex** [comment]
Hi @nadav96!

Here is how you can get the current pane folder, a file under the cursor, or all selected files:
```lua
-- Current pane folder
local currentFolder = context.activePane.model.folder
if currentFolder then
    martax.alert("Current folder: " .. currentFolder.path)
end

-- Single file under cursor
local fileUnderCursor = context.activePane.model.currentFile
if fileUnderCursor then
    martax.alert("File under cursor: " .. fileUnderCursor.path)
end

-- All selected files, or a single file under cursor if nothing is selected
for _, file in ipairs(context.activePane.model.activeFiles) do
    martax.alert("Active file: " .. file.path)
end
```

You can find several examples in the Tutorials section of the [API documentation](https://marta.yanex.org/api/).
