### ISSUE TITLE
Marta 0.8 Beta

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#688]
Hi everyone! I've been working on Marta 0.8 for quite a long time, and finally, I'm happy to share a beta version.

### New file system

In Marta 0.8, I rewrote the entire file system layer from scratch. It took enormous efforts; however, I'm thrilled with the result. Here's what I got:

* All file operations are guaranteed to be done in background. It brings more stability and even more snappy UI.
* Marta now gathers only the required file information, and at the predictable moment. It means the handling of massive file hierarchies became faster.
* Problems with navigation across symbolic links are solved. Now, when you enter a symlinked directory, Marta won't jump you to the original folder location. You can navigate through symbolic links as if they were ordinary folders.
* It became much easier to implement new file systems. Expect FTP/SFTP support, as well as improvements in archive handling shortly.

### New file operations

Together with the file system layer, async operations (Copy, Delete, Move to Trash, and so on) were rewritten from the ground up as well. Old implementations were straightforward and didn't support a lot of cases. The refactoring fixed many subtle bugs.

### Come get some!

As you might expect, such massive refactorings require thorough testing. Even though I spend a lot of time testing different scenarios, it's just impossible to cover everything. Please let me know if you find regressions.

### [Download Marta 0.8 Beta](https://github.com/marta-file-manager/marta-issues/files/5538023/Marta.app.zip)

There're a couple of UI glitches found on macOS 10.12. I plan to address them in the 0.8 release.
* Background of the query text field in Actions panel is too black in dark themes
* Hotkey overlay doesn't show in dialogs on pressing the "Option" key

### Changelog

* **New features**
    * File system and asynchronous operations are rewritten from scratch
    * Dialog hotkeys are now shown on holding "Option" key [#660](https://github.com/marta-file-manager/marta-issues/issues/660)
    * Implement proper navigation across symbolic links [#686](https://github.com/marta-file-manager/marta-issues/issues/686)
    * Play sound at the end of lengthy operations [#603](https://github.com/marta-file-manager/marta-issues/issues/603)
    * New actions
        * "Run actions" (runs several actions at once) [#638](https://github.com/marta-file-manager/marta-issues/issues/638)
        * "Close other panes" [#634](https://github.com/marta-file-manager/marta-issues/issues/634)
        * "Toggle selection" [#592](https://github.com/marta-file-manager/marta-issues/issues/592)
    * Breadcrumbs
        * Cmd+Click on breadcrumbs item should open the folder in the new tab [#661](https://github.com/marta-file-manager/marta-issues/issues/661)
        * Add "Open in New Tab" item to the breadcrumb context menu [#662](https://github.com/marta-file-manager/marta-issues/issues/662)
    * Allow specifying size format in different size units [#665](https://github.com/marta-file-manager/marta-issues/issues/665)
    * Display an actual icon for ".." list item [#102](https://github.com/marta-file-manager/marta-issues/issues/102)
    * Tabs for virtual folders are now more visible [#596](https://github.com/marta-file-manager/marta-issues/issues/596)
    * Add "Close other tabs" and "New tab" to the tab context menu [#566](https://github.com/marta-file-manager/marta-issues/issues/566)
    * Open .klib (Kotlin library) files as ZIP archives [#684](https://github.com/marta-file-manager/marta-issues/issues/684)
    * Allow specifying additional extensions for ZIP file system [#632](https://github.com/marta-file-manager/marta-issues/issues/632)
    * Suggest deleting files if the volume doesn't support trashing [#3](https://github.com/marta-file-manager/marta-issues/issues/3)
    * Hide files with a "hidden" attribute [#589](https://github.com/marta-file-manager/marta-issues/issues/589)
    * Add "all.applications" path variable [#561](https://github.com/marta-file-manager/marta-issues/issues/561)
* **Bugfixes**
    * "New directory/new file": the created file is not selected sometimes [#487](https://github.com/marta-file-manager/marta-issues/issues/487)
    * Fix macOS built-in search functionality in Help menu [#643](https://github.com/marta-file-manager/marta-issues/issues/643)
    * Caret isn't visible in preferences left editor [#639](https://github.com/marta-file-manager/marta-issues/issues/639)
    * Symlink files should have an arrow badge in ZIP archives [#683](https://github.com/marta-file-manager/marta-issues/issues/683)
    * Symlinks pointing to directories in ZIP archives should have a folder icon [#685](https://github.com/marta-file-manager/marta-issues/issues/685)
    * Select all (Cmd+A) doesn't work in Search Bar [#682](https://github.com/marta-file-manager/marta-issues/issues/682)
    * Analyze disk usage: Delete operation should affect the calculated size of folders [#681](https://github.com/marta-file-manager/marta-issues/issues/681)
    * Cached files should be deleted when the parent file system is disposed [#679](https://github.com/marta-file-manager/marta-issues/issues/679)
    * Don't prioritize base actions over ordinary one [#671](https://github.com/marta-file-manager/marta-issues/issues/671)
    * "Invert selection" action doesn't work properly if no items are selected [#653](https://github.com/marta-file-manager/marta-issues/issues/653)
    * Drag & Drop is active even if disabled in Preferences [#652](https://github.com/marta-file-manager/marta-issues/issues/652)
    * Duplicate path in "Analyze disk usage" action [#648](https://github.com/marta-file-manager/marta-issues/issues/648)
    * Delay on first context menu display [#647](https://github.com/marta-file-manager/marta-issues/issues/647)
    * Hotkeys in dialogs
        * Readline shortcuts (Ctrl+N or Ctrl+P) don't work in dialogs [#645](https://github.com/marta-file-manager/marta-issues/issues/645)
        * Copy/Paste hotkeys don't work in dialogs [#614](https://github.com/marta-file-manager/marta-issues/issues/614)
    * Marta forgets tab order on relaunch [#627](https://github.com/marta-file-manager/marta-issues/issues/627)
    * Glitch on opening Preview [#625](https://github.com/marta-file-manager/marta-issues/issues/625)
    * Can't remap Cmd+N [#623](https://github.com/marta-file-manager/marta-issues/issues/623)
    * "Open external terminal here" and "Go forward" shortcuts aren't updated in application menu [#617](https://github.com/marta-file-manager/marta-issues/issues/617)
    * listModelHandler extension broken in Lua API [#616](https://github.com/marta-file-manager/marta-issues/issues/616)
    * Wrong selection after renaming with the same name [#608](https://github.com/marta-file-manager/marta-issues/issues/608)
    * Use native keyboard shortcut handling [#504](https://github.com/marta-file-manager/marta-issues/issues/504)
    * CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car fault [#600](https://github.com/marta-file-manager/marta-issues/issues/600)
    * Unable to map Cmd+N hotkey [#383](https://github.com/marta-file-manager/marta-issues/issues/383)
* **Other changes**
    * Unify action identifier naming [#630](https://github.com/marta-file-manager/marta-issues/issues/630)
    * Change hotkey for "Show hidden files" action to `Cmd+Shift+.`, as in Finder [#658](https://github.com/marta-file-manager/marta-issues/issues/658)
    * Disable system accent selection color by default [#666](https://github.com/marta-file-manager/marta-issues/issues/666)
    * Return text field focus ring back [#649](https://github.com/marta-file-manager/marta-issues/issues/649)
    * Update tutorial screenshots [#673](https://github.com/marta-file-manager/marta-issues/issues/673)
    * Update libarchive to 3.4.3 [#656](https://github.com/marta-file-manager/marta-issues/issues/656)
    * Update liblzma to 5.2.5 [#655](https://github.com/marta-file-manager/marta-issues/issues/655)
    * Update libzip to 1.7.3 [#654](https://github.com/marta-file-manager/marta-issues/issues/654)

**Comment by igor-krupenja** [comment]
After a few days of use, I do not really see anything major. Ac ouple of minor things I came across (both are new I think):

1. Low contrast in Look Up with a focused item (text barely legible against blue background):
![image](https://user-images.githubusercontent.com/26354715/100379528-bc85c400-301d-11eb-9463-6a18c0dc55cb.png)
2. Poor contrast in Settings for deprecated setting (black text against the brownish background):
![image](https://user-images.githubusercontent.com/26354715/100379678-edfe8f80-301d-11eb-9cfd-6fbb608b8a95.png)

Both are with Classic theme.

**Comment by bradsucks** [comment]
Been using it for two weeks and haven't had any issues. It's excellent, thanks yanex

**Comment by yanex** [comment]
@igor-krupenja @bradsucks Thanks for testing! I'll fix the bugs Igor mentioned.

**Comment by yanex** [comment]
Here's the release candidate. It would be great if you could check it.

### [Marta RC1.zip](https://github.com/marta-file-manager/marta-issues/files/5609221/Marta.RC1.zip)

Changelog:
* **New features**
	* "Inverse ordering" action [#694](https://github.com/marta-file-manager/marta-issues/issues/694)
	* "Ordering" action now accepts arguments [#692](https://github.com/marta-file-manager/marta-issues/issues/692)
* **Bugfixes**
	* Can't move files across volumes [#622](https://github.com/marta-file-manager/marta-issues/issues/622)
	* Scroll position on new directory load should always be reset to zero [#689](https://github.com/marta-file-manager/marta-issues/issues/689)
	* Search bar: poor contrast as `useSystemAccentColor` was accidentally enabled by default
	* Preferences editor: poor contrast with error/warning highlighting
* **Other changes**
	* Touch Bar icons now look HIG-compatible [#693](https://github.com/marta-file-manager/marta-issues/issues/693)
	* `useSystemAccentColor` configuration key is deprecated

**Comment by bradsucks** [comment]
RC1's running great here so far. New file ordering shortcuts work great, thank you!

**Comment by igor-krupenja** [comment]
Also see no issues with the new RC build. btw, the new touch bar icons look really cool 👍
