### ISSUE TITLE
Ordering via keyboard shortcuts

### ISSUE THREAD

**Issue by bradsucks** [marta-file-manager/marta-issues#692]
Is it possible to change the file listing order via keyboard shortcut? Previous file manager I used you could use CTRL 1-6 to toggle sorting via name, date, etc. Hitting the shortcut twice would toggle ascending/descending. It was handy.

**Comment by yanex** [comment]
Starting from Marta 0.8, you will be able to add arguments to the `core.ordering` action.
In later versions of Marta, there will be a way to easily get all supported arguments for each action. For now, I'll put some explanations below.

Add a new binding using the extended action specification:

```
keyBindings {
    "Ctrl+1" {
        id "core.ordering"
        ordering "name"
    }
    "Ctrl+2" {
        id "core.ordering"
        ordering "size"
    }
}
```

Supported arguments are:
- `ordering` (string) – can be `name`, `extension`, `size`, `created`, `modified`, `added`.
- `isFolderOnTop` (optional, boolean) – if `true`, folders are shown on top of other items.
- `isAscending` (optional, boolean) – if set, specifies sorting order. If not set, "hitting the shortcut twice would toggle ascending/descending".

**Comment by h0tk3y** [comment]
@yanex

> isFolderOnTop (optional, boolean) – if true, folders are shown on top of other items.

In 0.8.1, the `isFolderOnTop` argument doesn't work for me any longer, while unsetting the corresponding checkbox in the `Ordering` dialog works as expected. Has the argument name changed?

**Comment by page-down** [comment]
@h0tk3y 
Open Preferences and check the default configuration on the left. I think it should be `showFoldersOnTop`.

https://marta.sh/docs/configuration/hotkeys/
- Action Arguments
  - Ordering
    - showFoldersOnTop – `true` if folders should be displayed above files.

**Comment by h0tk3y** [comment]
@page-down Thanks! `showFoldersOnTop` worked just fine.
