### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by user3587412** [marta-file-manager/marta-issues#696]
Thank you for continuing to update and improve Marta.

Are there near plans on shipping a universal binary/Apple Silicon version of Marta?

**Comment by yanex** [comment]
I can build a native binary for Apple Silicon rather soon, but I don't have the hardware to test it. I wonder if providing untested artifacts is better than not providing them at all. Marta doesn't do any CPU-intensive things, so the x86 version under Rosetta 2 should work considerably well.
However, I hope I will be able to borrow a MacBook with Apple Silicon in the meantime and test Marta on it thoroughly. Alternatively, if someone who sees this comment owns the new hardware and is OK with testing a preview version of Marta on it, I can share the build here.

**Comment by user3587412** [comment]
The x86 version under Rosetta 2 indeed does work really well. The initial launch took less than a second for me (other apps take around 5 to 10 seconds for the initial launch for translation). I own the new Macbook Air and I would be totally OK with testing a preview version.

**Comment by mbirth** [comment]
I've got the MBP M1 and also would like to test the preview version. :)

**Comment by alexfreud** [comment]
I can test on Apple M1 :)

**Comment by likidu** [comment]
Please count me in for the Apple M1 testing as well, as a daily user of Marta ;)

**Comment by vladstudio** [comment]
I can test on Apple M1 too! And +1 for M1 version -- it just feels better to know your apps are not Rosetta :-)

**Comment by artemlazaruk** [comment]
Will test it as well. Thank you for your work.

**Comment by brandondrew** [comment]
I can also test on the M1.  

And I also noticed that it's running very quickly under Rosetta, but I'd be happier if all of my Rosetta apps could be upgraded to use the M1 natively.  Even though Marta is extremely efficient, I still think it's worth the effort.

**Comment by yanex** [comment]
Sorry for the long wait! I've just released [Marta 0.8.1 Beta 1](https://github.com/marta-file-manager/marta-issues/issues/750), and it should fully support Apple Silicon.
Unfortunately, I still don't have M1 so it would be great if someone could confirm that it works :-)

Please check:
- The "Check for Updates…" action – it should display that your version is the newest one;
- ZIP archive support – it should open archives correctly;
- 7Zip/tar.gz archive support – it also should open archives correctly;
- Lua API – a plugin from the "Final version" section of the [tutorial](https://marta.sh/tutorials/your-first-marta-plugin#final-version) should add the "Hello world" action.

**Comment by vladstudio** [comment]
@yanex  - what a coincidence, I just used Marta today to clean up a bunch of old HDDs, after abandoning it for a while, and it's been a joy!

Everything seems to work fine in Beta 1 on MacBook Air M1:
* The "Check for Updates…" action – "You are currently running version 0.8.0.0.1."
* ZIP archive support – opened and browsed several Zip packages successfully;
* sorry, no 7Z files around;
* the plugin worked fine.

**Comment by yanex** [comment]
@vladstudio Great, many thanks for checking!

**Comment by holograph** [comment]
Some more field tests of 0.8.1 beta 2 behavior on M1 (1st gen Macbook Air with 8-core Apple Silicon running Big Sur 11.3.1 (20E241)):

* Check for updates works
* zip archives work perfectly in my testing
* 7z archives (created via brew-installed p7zip) work perfectly
* Plugin worked perfectly

Yay!!
