### ISSUE TITLE
F Keys cannot be remapped

### ISSUE THREAD

**Issue by Strandbummler** [marta-file-manager/marta-issues#699]
I tried to remap some F-Keys, but they just keep their standard keybinding.
i.e. I tried to remap F2 like:
`F2 {
        id "core.history"
    }`
I made sure that it there where no other bindings for F2 but it just keeps refreshing the current directory.

**Comment by Strandbummler** [comment]
It seems, as this only occurs with core.history. For whatever reason.

**Comment by yanex** [comment]
`core.history` was renamed to `core.recent.directories` quite a long ago (and now it's finally `core.recent`). When did you find such an identifier?

**Comment by Strandbummler** [comment]
It was part of the config file. I merely copy pasted it. Thanks, much appreciated.

**Comment by yanex** [comment]
Thanks! Then I'll close the issue. Please feel free to file a new one if there are problems with mapping other actions.
