### ISSUE TITLE
Big Sur: Corners of the action bar don't match new window corners

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#701]
<img width="458" alt="Screen Shot 2020-12-03 at 23 21 15" src="https://user-images.githubusercontent.com/95996/101036414-5de0bd00-35be-11eb-9954-8cf4a9190584.png">

**Comment by lytoooo0** [comment]
The corner of _action bar_ (⌘ ⇧ P) and _look up_ bar (⌘ P) aren't round.
![image](https://user-images.githubusercontent.com/34278289/101512379-e6dc6780-39b5-11eb-8b8d-4a2fa5799b73.png)

![image](https://user-images.githubusercontent.com/34278289/101512397-efcd3900-39b5-11eb-845c-d57b9d201a86.png)
