### ISSUE TITLE
Marta 0.8, analyze disk usage does not work

### ISSUE THREAD

**Issue by vinbrule** [marta-file-manager/marta-issues#709]
Hi,
In Marta 0.8, that function does not work anymore. It is still fine in 0.71. I am using Catalina. Here is the screen recording
[https://monosnap.com/file/dDQlL2HgBbPLmpRJBML99h5KRZf8ee](url)

**Comment by yanex** [comment]
Hello @vinbrule! I fixed a couple of bugs that affected "Analyze Disk Usage", plan to release them as a part of Marta 0.8.1.
