### ISSUE TITLE
Save current tab position on reload

### ISSUE THREAD

**Issue by weranda** [marta-file-manager/marta-issues#710]
Приветствую, Ян.

Классный, удобный, легковесный, а главное (для меня) — быстрый файловый менеджер.
Заметил одну особенность работы и не знаю, так ли должно раборать?

1. Открываю две или более вкладок.
![1](https://user-images.githubusercontent.com/9132570/101914260-20d78480-3bd5-11eb-9004-7433be8f0f04.png)

2. Устанавливаю активной любую вкладку, но не крайнюю правую.
![2](https://user-images.githubusercontent.com/9132570/101914267-2503a200-3bd5-11eb-9cb9-5d590f0f380a.png)

3. Закрываю файловый менеджер крестиком (не cmd+q).
![3](https://user-images.githubusercontent.com/9132570/101914281-292fbf80-3bd5-11eb-8a9a-374ee47d3dcd.png)

4. Открываю файловый менеджер и ранее активная вкладка смещается в крайнюю правую позицию. 
![4](https://user-images.githubusercontent.com/9132570/101914289-2b921980-3bd5-11eb-8d3e-750bd125b5b8.png)

Есть ли алгоритм запоминания вкладок в ФМ Marta?

**Comment by yanex** [comment]
English translation: 

On application restart, Marta activates the first tab on the left, regardless of which tab was selected when the application was shut down. The goal is to remember the open tab.
