### ISSUE TITLE
Add option to Navigate to Original File in Inactive Pane

### ISSUE THREAD

**Issue by igor-krupenja** [marta-file-manager/marta-issues#717]
currently, for symlinks, there are:
- Navigate to Original File in New Tab
- Navigate to Original File

Those are super useful, though I was thinking that adding an option to navigate to original file in the other **pane** would be nice as well

**Comment by yanex** [comment]
"Navigate to Original File" should support the `mode` parameter with at least these possible values:
`default` – open in the current pane;
`newTab` – open in the new tab (and activate the tab);
`newTabInactive` – open in the new tab but stay in the current one;
`inactivePane` – open in the inactive (other) pane;
`newWindow` – open in the new window.
