### ISSUE TITLE
Escape key not present on touch bar

### ISSUE THREAD

**Issue by bdcarr** [marta-file-manager/marta-issues#722]
Hello! It's not possible to exit quick select when using a laptop with a touch bar, because the Escape key doesn't show up. Could we add that in on the side? Looks like there's space for it.

![image](https://user-images.githubusercontent.com/1940488/104795154-5557e500-5800-11eb-811f-088a82eae145.png)

**Comment by yanex** [comment]
Hello @bdcarr,
Normally, the Escape button should be shown. Did you disable it by yourself or by using a third-party software?
It seems you have the first generation of Touch Bar. Here's how it should look like:

<img width="1104" alt="Screen Shot 2021-01-16 at 13 54 54" src="https://user-images.githubusercontent.com/95996/104797599-c0a2b680-5802-11eb-8db0-4705e083901f.png">

**Comment by bdcarr** [comment]
Oh, what do you know! It's gone from everywhere else too. Not sure how that happened, I don't have any customisations 🤔 

Anyway thanks, def an issue on my end.
