### ISSUE TITLE
Enter into any file as in archive

### ISSUE THREAD

**Issue by dkBrazz** [marta-file-manager/marta-issues#727]
There are many file formats that are archives (usually zip) - *.jar, *.docx, *.idml, and so on
Some of these file extensions are opened with proper software, some are not associated with anything

Sometimes I need to treat such files as archives and look at what is inside, or even modify them.

I would like to have a key-binding that forces Marta to treat any file as an archive and try to enter into it.
While [Enter] still does the default action on the file

It should be easy if Marta is able to detect archive type on the fly by the MagicNumber

**Comment by yanex** [comment]
In Marta 0.8.1 there will be an action called "Open As…" that will allow entering some other path extension (such as "zip" instead of "epub" or "docx"). According to the entered extension, new applications and handlers will be shown.
