### ISSUE TITLE
Is there any url or osascript to open marta in some specific directory?

### ISSUE THREAD

**Issue by yqrashawn** [marta-file-manager/marta-issues#73]
Need to go in folders easily, favorites and history are not good enough and can't do it outside the app.

**Comment by yanex** [comment]
You can launch Marta from CLI as described here: https://marta.yanex.org/docs#using-from-command-line. Note that you do not have to create symlinks, this will work as well:

`/Applications/Marta.app/Contents/Resources/launcher /Users /`

By the way, if there are any specific usability problems with Favorites or History, please create issues for them.

**Comment by yqrashawn** [comment]
Thx. Forget that.
Is there anyway to change the quick select key '/'?
