### ISSUE TITLE
Setting To Not Show File Extension

### ISSUE THREAD

**Issue by JosephTLyons** [marta-file-manager/marta-issues#740]
Is there a way to turn off extensions in Marta?  I didn't see one, but its possible I missed it.

If not, it would be nice to be able to do that.  A simple on/off setting would probably suffice, but being able to provide a list of extensions you didn't want to show up might be nice.  For instance, a user could specify ".app" in the list of file types to not display extensions for, then the the apps folder would not show the extension ".app" but all other file types would still show up.

**Comment by marvelph** [comment]
I'm using "Edit columns" to display file extensions, so if file name extensions are displayed, they are duplicated.
If you can hide the file name extension, I would be happy.
