### ISSUE TITLE
Question: Is there a way to instantiate the IntRange class in a plugin?

### ISSUE THREAD

**Issue by marvelph** [marta-file-manager/marta-issues#754]
I want to call ListModel:select(), but I cannot find a way to instantiate the range.

**Comment by yanex** [comment]
Thanks for noticing the bug! It supposed to work as:

```lua
context.activePane.model:select({from = 2, to = 4})
```

However, in 0.8 there's a bug that prevents this from working properly. I'll fix it in 0.8.1 which will be out pretty soon.

**Comment by marvelph** [comment]
@yanex  Thanks for the reply.
I'll try 0.8.1.

**Comment by marvelph** [comment]
@yanex I tried 0.8.1 RC.
ListModel:select() is working fine.
I found one behavior that bothered me.
It seems to crash Marta when the IntRange exceeds the range of the ListModel.
