### ISSUE TITLE
Question:Is there a setting to output runtime errors and debug prints of plugins to the console?

### ISSUE THREAD

**Issue by marvelph** [marta-file-manager/marta-issues#756]
I want to debug a plugin in Marta 0.8, but runtime errors and debug prints are not output to system.log in the console.
Is there a setting to enable output to system.log?

**Comment by marvelph** [comment]
It is not possible to display the system.log in the Console, but debugging is now possible by launching Marta from Terminal.

**Comment by yanex** [comment]
Hm, that's strange. For the following plugin, I can see the `print()` output in the Console.

```lua
plugin {
    id = "marta.example.helloworld",
    name = "Hello world",
    apiVersion = "2.0",
    author = "John Smith"
}

action {
    id = "action",
    name = "Hello world",
    apply = function(actionContext)
        print("Hello world!")
    end
}
```

<img width="1400" alt="Console" src="https://user-images.githubusercontent.com/95996/126126742-8d26c5fc-17cc-4c8e-9a12-e84bcaed4223.png">

However, your solution is also very handy! Let me add it to the documentation :-)

By the way, in case if you need full-fledged debugging experience, you can use [mobdebug](http://localhost:1313/tutorials/debugging-plugins/#mobdebug). It is supposed in ZeroBrane Studio, and I've also tried it in IntelliJ IDEA and it worked there as well.

**Comment by marvelph** [comment]
Thank you for preparing the images.
I was able to realize my mistake.

I had assumed that the output would be in the "system.log" shown at the bottom of the report on the left.
I selected the Mac listed under "Devices" and hit "Start" to see the "Malta" log.

>By the way, in case if you need full-fledged debugging experience, you can use mobdebug.

I'll give it a try.

**Comment by marvelph** [comment]
@yanex 

In order to debug an action, I think the documentation should mention that `require('mobdebug').on()` is required at the top of the Apply function.
