### ISSUE TITLE
Favorites aren't applied after editing

### ISSUE THREAD

**Issue by holograph** [marta-file-manager/marta-issues#757]
Marta latest beta 2 (shows version 0.8.0.0.2)

Quick (and hopefully trivial) bug:
1. Edit favorites
2. Make some changes
3. Save and close the editor
4. Open the favorites dialog

Result: previously loaded favorites list is shown
Expected: the list is shown with the edits applied

**Comment by yanex** [comment]
Thanks! Will be fixed in 0.8.1 RC.
