### ISSUE TITLE
Is there a way to check whether the active panel exists on the left or right side of the window in a plugin?

### ISSUE THREAD

**Issue by marvelph** [marta-file-manager/marta-issues#758]
I'm trying to create a plugin that behaves differently depending on whether the active panel is on the left or right side of the window.
For example, "Clone to Left".

How do I know if the active panel is on the left or the right?

**Comment by yanex** [comment]
Use the [TabManager:getPosition()] method:

```
action {
    ...
    apply = function(context)
        local tabManager = context.window.tabs
        martax.alert(tabManager:getPosition(context.activePane))
    end
}
```

**Comment by marvelph** [comment]
Thanks @yanex .
I was able to implement what I wanted.

```
action {
    id = "change.current.pane.left",
    name = "Change Current Pane to Left",
    apply = function(context)
        local tabManager = context.window.tabs
        if tabManager:getPosition(context.activePane) == "right" then
            tabManager:activate(context.inactivePane)
        end
    end
}
```

I have two questions for you.

I used TabManager:activate() to change the current panel, but PaneContext:activatePane() did not work.
Are there different uses for these two?

I want to compare the result of TabManager:getPosition() with TabPosition.right instead of the string “ right", can I use an enumeration constant?

**Comment by yanex** [comment]
> I used TabManager:activate() to change the current panel, but PaneContext:activatePane() did not work.
> Are there different uses for these two?

Hmm, it seems the documentation was telling a lie. The correct name is `activateTab()`. I will update the reference page together with the 0.8.1 release.

> I want to compare the result of TabManager:getPosition() with TabPosition.right instead of the string “ right", can I use an enumeration constant?

Currently, you need to pass string literals. I'll add proper enum mapping in the future version (https://github.com/marta-file-manager/marta-issues/issues/759).

**Comment by marvelph** [comment]
>The correct name is activateTab().

Thanks.
activateTab() worked as expected.

>Currently, you need to pass string literals.

I understand.
