### ISSUE TITLE
Menu items related to tabs and windows should be placed in the File menu.

### ISSUE THREAD

**Issue by page-down** [marta-file-manager/marta-issues#763]
Menu items such as New Tab, New Window, Close Tab, and Close Window should be placed in the File menu.

Please refer to the common macOS software menu item location.

If there is no special reason, it is still recommended to follow the conventional design.

Although I personally never use the menu.

**Comment by yanex** [comment]
While a lot of applications put "New Window" or similar items to the "File" menu, I don't think it makes any sense, unless the application deals with documents (e.g. TextEdit.app). You don't create any files when you choose "New Window" or "New Tab". Also, it's very inconvenient and counter-intuitive to have some items related to windows/tabs in the "File" menu, and others in "Window".

So I will close the issue as "as designed".

**Comment by page-down** [comment]
First of all, I agree with your point of view.

However, I don't recall any macOS application putting the menu items for creating and closing windows and tabs in the "Window" menu. This is not limited to file-oriented applications, but also covers other browsing applications. This is something that just doesn't feel right when you open the menu as a regular macOS user.

In addition, the menu is fully customizable, and the suggestions made here are only for the "default" settings.

The reason I bring this up is to make more macOS eco-users feel "at home" when using Marta. And hopefully more users will stay and become a paid user after `1.0.0`.

As you mentioned in another Issue:
> Of course, I can't guarantee it will change my mind, but I feel it's important to see the whole picture.

I respect your choice and hope to bring some different perspectives to the table.
