### ISSUE TITLE
[Feature Request] Support scrolling navigation breadcrumb bar by mouse vertical scroll

### ISSUE THREAD

**Issue by page-down** [marta-file-manager/marta-issues#768]
For now, the items at the start of the breadcrumb navigation bar are not visible when entering the ultra-deep directory.

Unable to jump to the root path by mouse click.

**Comment by page-down** [comment]
Below is a screenshot

This issue has also been troubling for a long time.

```shell
mkdir -p /tmp/https/github.com/marta-file-manager/marta-issues/issues/768/issue-952034257/more-level/another-level/marta-file-manager/marta-file-manager/marta-file-manager/marta-file-manager
```

![image](https://user-images.githubusercontent.com/57713011/126865706-df0822a3-a9e7-4a74-a653-4afe30c870bd.png)

**Comment by marvelph** [comment]
I see that the breadcrumb list can be scrolled left and right.

**Comment by page-down** [comment]
> I see that the breadcrumb list can be scrolled left and right.

Oh, thanks, after trying I can use Shift + mouse scrolling.

I have changed the title to:
Support scrolling navigation breadcrumb bar by mouse vertical scroll

For example, the Finder also supports vertical mouse scrolling when there are too many tabs.

@yanex 
Please evaluate this suggestion when you have time, thanks! I hope Marta will continue to improve.
