### ISSUE TITLE
Selection should be on the `..` item by default.

### ISSUE THREAD

**Issue by DanPristupov** [marta-file-manager/marta-issues#77]
Hi!

Thank you for the awesome file manager.

I'm not sure if it's a bug or a feature. Currently when I open a directory, focus in the file list will be on the first item, not on the `..` entry (like in NC/TC). It seems to be unnatural for me. Is it an intentional behavior?

**Comment by yanex** [comment]
Hello! Thank you for using Marta!

The first non-`..` item is selected by default because you can always press `Backspace` to go up. But if you do not like this behavior, you can change it in the configuration:

```json
"behavior": {
    "table": {
        "selectGoUpDirectoryOnEnter": true
    }
}
```

Also see `Cmd+Shift+O`, "Open default configuration" for more configuration options.

**Comment by DanPristupov** [comment]
Thanks, `selectGoUpDirectoryOnEnter` made the trick.
BTW, `Cmd+Shift+O` does nothing on my system.

**Comment by yanex** [comment]
@DanPristupov Oh, it was about `Cmd+Shift+P`, of course.

**Comment by DanPristupov** [comment]
@yanex awesome! Already learned a lot from this view 👍
