### ISSUE TITLE
Remove support for macOS 10.12 (Sierra) and 10.13 (High Sierra)

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#786]
Unless some miracle happens, 0.8.1 is going to become the latest version of Marta that supports macOS 10.12 and 10.13.

There are several reasons for this decision:

- A lot of UI components work differently in older versions of macOS. Almost every time I implement some new UI, I need to fix numerous issues, so the application behaves well enough on Sierra. It takes quite a lot of time and prevents me from using modern Cocoa API. The last time I had to spend a whole day fixing a problem with breadcrumbs, and the solution involved utterly dirty hacks with Objective-C method implementation swapping.
- I don't have the hardware which can run Sierra natively. So I use Parallels Desktop to test Marta on this OS, and the experience is far from agreeable. In particular, rendering there is very buggy and choppy. I often have to guess if I need to fix a specific bug or it arises because of a bad environment.
- Very few people use mentioned macOS versions. Also, they certainly do it for a reason, and they are very unlikely to migrate in a year or two.

Nevertheless, if you use Sierra or High Sierra, please write why you can't update the OS in the comments. Of course, I can't guarantee it will change my mind, but I feel it's important to see the whole picture.

**Comment by skojin** [comment]
I personally use 10.12 because I have mac book 2015 and don't want update OS because it works. But I think it more important to improve this awesome manager than keep support of old OS version. Move on!
