### ISSUE TITLE
How to access disks and favorite locations

### ISSUE THREAD

**Issue by danielo515** [marta-file-manager/marta-issues#821]
Hello, sorry if the question is stupid, but, how can I open a mounted disk?
In finder it is very easy, there is a section on the left where all my mounted disks appear. However, on Marta I don't have an idea of how to access them. Is it possible to have something like a sidebar with all my disks and favorite locations to access them quickly?

**Comment by danielo515** [comment]
Ok, I see you can access volumes by opening the command palette and select volumes. I still think it will be valuable to have something "visible"to access them, since I have plenty of screen space but not excessive memory.

**Comment by page-down** [comment]
There are several ways:

- Menu "Go" -> "Volumes"
- Default keyboard shortcut
  - volumes: Option+1
  - favorites: Option+2
- Add a button to the ActionBar
```
setup {
    actionBar [
        "core.volumes"
    ]
}
```
- You can also add `/Volumes` to your favorites and open them quickly.

It is also possible to develop your own GUI plugin. The official sidebar has not yet been implemented. ( Issue: #320 )

**Comment by danielo515** [comment]
Thanks, that works.
I'll be subscribing to the issue #320
