### ISSUE TITLE
Actions menu keyboard shortcut does not seem configurable

### ISSUE THREAD

**Issue by IgorKrupenja** [marta-file-manager/marta-issues#825]
What is the correct way of changing Actions... keyboard shortcut (Cmd+Shift+P by default)?  I have tried going to System Preferences -> Keyboard -> Shortcuts -> App Shortcuts and setting the shortcut there. It seems to be assigned correctly as I get the correct key combination (Cmd+P) in the menu:

![image](https://user-images.githubusercontent.com/26354715/131257433-5aefff00-a49c-4b3e-a4aa-c242b04b1e97.png)

However, actually pressing Cmd+P still opens Look up (and Cmd+Shift+P still opens Actions).

Workaround is to use something like BetterTouchTool but was wondering if there is a built-in method of doing this and I just missed something 🙂

**Comment by page-down** [comment]
First remove all Marta shortcut configurations in system preferences.
> macOS: System Preferences -> Keyboard -> Shortcuts -> App Shortcuts

Then configure the shortcuts in Marta's own Preferences.

The default configuration is shown on the left, add keyboard shortcuts that need to be redefined on the right.

```
keyBindings {
    "Shift+Cmd+P" "core.actions"
    "Cmd+P" "core.lookup"
}
```
