### ISSUE TITLE
Website: The links in the docs have been broken for a while

### ISSUE THREAD

**Issue by page-down** [marta-file-manager/marta-issues#828]
The link in the document [Marta Docs](https://marta.sh/docs/) is not accessible.

Panes and Tabs
https://marta.sh/docs/core/panes/

Visiting this link above returns a 404 error.

Is there a public Git repository for user manual docs, API references, and development documentation? Thanks.

**Comment by yanex** [comment]
Fixed the links, thanks!
Currently, the website repository is not public.
