### ISSUE TITLE
After Analyze Disk Usage columns still labeled as sorted by name

### ISSUE THREAD

**Issue by gamedeviced** [marta-file-manager/marta-issues#833]
### Problem

After using Analyze Disk Usage the new tab is sorted by size. But the columns are still labeled as sorted by name.

<img width="510" alt="Bildschirmfoto 2021-09-23 um 12 58 10" src="https://user-images.githubusercontent.com/70090026/134495909-e2e58246-9efb-4277-94f0-10fe8c0c92d8.png">

### Steps to reproduce

1. Open Marta version 0.8.1
2. Run Analyze Disk Usage via Actions

### Expected behaviour

The size column should be labeled as sorted by.

**Comment by page-down** [comment]
Reported on August 16, 2021 and not yet resolved.

https://github.com/marta-file-manager/marta-issues/issues/815#issuecomment-899203444
