### ISSUE TITLE
Lua API: Allow running other actions with arguments

### ISSUE THREAD

**Issue by twio142** [marta-file-manager/marta-issues#851]
For now the function `WindowContext:runAction()` allows to call another action, but not to provide arguments with it. 

Say, to select all files matching the quick select string, I'll need to run the `Select Group` action with `context.activePane.model.quickSelect`.

And by setting a keybinding in the config file to specify the argument for `core.select.group`, there's no way to provide the current entered quick select string.

(Any ideas how to implement that right now?)

**Comment by yanex** [comment]
Hello, @twio142!
Starting from 0.8.2, it will be possible to create a custom `ActionContext` where you can pass the arguments (#816).
As I think this issue duplicates #816, let me close it.
