### ISSUE TITLE
Support Forward/Back keys for generic mouses

### ISSUE THREAD

**Issue by ursusursus** [marta-file-manager/marta-issues#855]
Hi, Im a brand new mac user.
I have a logitech G403 mouse with back and forward buttons, which do work for example in Chrome, but not in Marta.

How would I bind those?

**Comment by forivall** [comment]
I have a logitech mx master 3, and it works fine for me. Perhaps you could use logitech's software to map your buttons to keyboard shortcuts for just marta? Not sure if the G-Series software supports that, but it might.

**Comment by yanex** [comment]
When installed, Logitech software emulates swipe events for Forward/Back key presses. However, out-of-the-box, events arrive as "other" mouse events.
