### ISSUE TITLE
What does the `>size` mean?

### ISSUE THREAD

**Issue by chrisgrieser** [marta-file-manager/marta-issues#907]
as opposed to the other table columns, "size" does have the `>` prefixed. removing it doesn't seem to do anything, and the docs also do not mention what the `>` does?

**Comment by page-down** [comment]
> Column specification format: [alignment]columnName[:size]. Alignment is either > (align to right) or < (align to left). ...

https://marta.sh/docs/core/columns/

**Comment by chrisgrieser** [comment]
ah, I see. my bad, overlooked it, since I only clicked at `Panes and Tabs` which was a dead link, making me assume that the sublinks were also dead (which, they are not 🤦 )

Thanks!
