### ISSUE TITLE
Where is preferences file location?

### ISSUE THREAD

**Issue by lenguyenthanh** [marta-file-manager/marta-issues#910]
Thanks for great this app. I just tried it and it seems wonderful.

I would love to know where the `preferences file` is stored so I can share it between my machines.

Best,
Thanh

**Comment by page-down** [comment]
Execute the `Open Configuration Folder` action (Shift+Cmd+P) and you will see the config file `conf.marco` under `~/Library/Application Support/org.yanex.marta/`.

**Comment by lenguyenthanh** [comment]
thanks @page-down
