### ISSUE TITLE
Quick select - Hide non-matching files/directories

### ISSUE THREAD

**Issue by martinsvoboda** [marta-file-manager/marta-issues#917]
Hi! First of all thank you for very good software.

I would suggest one feature for quick select. When using quick select Marta only highlights matched files. Which seems usefull for quick navigation, but for directories with many files is more convinient to hide non-matching files/directories.

Similar feature has Total Commander for windows or Nimble Commander on mac.

**Comment by page-down** [comment]
This suggestion has been previously posted and labeled as `feature`.

https://github.com/marta-file-manager/marta-issues/issues/772

> ... use this search box, brought up by "/", to activate filter mode and show only matches in the file list.

**Comment by cpresse** [comment]
There is already an option for that, just add that:

```
behavior {
    quickSelect {
        filterMatchedItems true
    }
}

```
Default setting is false.

**Comment by martinsvoboda** [comment]
@cpresse you are right. Works like a charm!
