### ISSUE TITLE
`globalFilter` not working

### ISSUE THREAD

**Issue by chrisgrieser** [marta-file-manager/marta-issues#919]
I am referring to the configuration  `behavior → files → globalFilter → name`, which does not seem to work. the default value, `"^(?!\\.DS_Store$).*$"`, which presumably is supposed to hide those pesky `DS_Store` files, actually does not hide them. 

I tried setting up my own regex for hiding certain files, but none of them were working. 

---

also on a small side note, I'd suggest renaming that setting, since "name" is ambiguous on whether it *includes* or *excludes* to regex. Also, as the default regex implies that it indeed means "include", I would suggest making it an exclude-filter.

**Comment by page-down** [comment]
This issue has been previously posted and has been marked as resolved in 0.8.2.
However, version 0.8.2 has not yet been released.

https://github.com/marta-file-manager/marta-issues/issues/827

**Comment by chrisgrieser** [comment]
Oh missed that one, thanks
