### ISSUE TITLE
How to restore regex quickSelect when it's not activated on every char

### ISSUE THREAD

**Issue by eugenesvk** [marta-file-manager/marta-issues#933]
Per your docs I've enabled shortcuts without modifiers and disabled quickSelect
```
behavior {
	quickSelect {
        activateOnAnyCharacter true
    }
}
```

So regular Quick Select commands now works on <kbd>/</kbd>, but then how would I invoke the regex Quick Select command now that was previously bound to <kbd>/</kbd>?
The substring Quick Select <kbd>\\</kbd> also stopped working.

I guess I might need an action `core.quick.select` or something where I'd be able to pass various options (regex/substrng/...) so that I could bind it to some other key, but couldn't find such an action (by the way, is here an exhaustive list of all actions or is it only in the default config + Actions Panel?)

**Comment by page-down** [comment]
> ... how would I invoke the regex Quick Select command ...

In the following issue it has been suggested that each mode can be activated with custom shortcuts.
https://github.com/marta-file-manager/marta-issues/issues/790

> ... so that I could bind it to some other key ...

I have suggested in the following issue that the keys used to activate the quick selection should be configurable.
https://github.com/marta-file-manager/marta-issues/issues/791

> ... is here an exhaustive list of all actions ...

yanex replied in July 2021:

https://github.com/marta-file-manager/marta-issues/issues/750#issuecomment-885046516

> In the future, there'll be an action that shows all actions together with their descriptions, identifiers, and a list of available parameters

I suggest that it should be automatically generated in the document.
It is inconvenient if you need to press a shortcut key (to perform an action) to see all the actions.
So far there is no list of all actions.

**Comment by eugenesvk** [comment]
Thanks a bunch for your references!
I guess only the last item for a full list of actions is not tracked anywhere, right? But it's planned anyway, so not worth it keeping the issue opened
