### ISSUE TITLE
api: do tabs have unique ids that don't change when a tab's position changes?

### ISSUE THREAD

**Issue by eugenesvk** [marta-file-manager/marta-issues#970]
I was trying to tweak a function that closes duplicate tabs and bumped into https://github.com/marta-file-manager/marta-issues/issues/969, so was wondering: is there a way to get a permanent unique tab's id that doesn't change when tab's position changes?

**Comment by page-down** [comment]
> ... get a permanent unique tab's id ...

In the Marta API, the so-called `tab` is actually a `PaneContext`, so the unique ID is its `id` property.

https://marta.sh/api/marta/panecontext.type/id/
